### ISSUE TITLE
'mem_limit' with a suffix does not work (e.g. 50M)

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-cli#1]
The following works fine with `docker-compose up`

```
web:
    image: nginx
    ports: 
        - "80:80"
    mem_limit: 50M
```

When using `ecs-cli compose up` I get the following error repeated 3 times:
`FATA[0000] Unable to create and read ECS Compose Project  error=strconv.ParseInt: parsing "50M": invalid syntax`

You can work around this by using

```
web:
    image: nginx
    ports: 
        - "80:80"
    mem_limit: 52428800
```

instead.
