### ISSUE TITLE
Question - how to communicate between docker compose services in fargate

### ISSUE THREAD

**Issue by ShaharMynd** [aws/amazon-ecs-cli#1005]
Hey,
I have a docker-compose file that has two services that need to communicate with one another within ECS Fargate.
My docker-compose file looks something like this:
```
version: '3'
services:
  av:
    image: ....
    ports:
      - "3310:3310"
    networks:
      - outpost_network
    container_name: av
    restart: unless-stopped
  app:
    build: 
      context: ./
      dockerfile: node.Dockerfile
    container_name: app
    depends_on: 
      - av
    networks:
      - outpost_network
    command: node app.js
networks:
  outpost_network:
    driver: bridge
```
This is how my ecs-params.yml looks:
```
version: 1
task_definition:
  task_execution_role: *******
  ecs_network_mode: awsvpc
  services:
    av:
      essential: true
    app:
      essential: true
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - *******
        - *******
      security_groups:
        - ******
      assign_public_ip: DISABLED
```
From inside the app I send requrests to av:3310 and get a response, no problem at all when I try to run it locally.
On fargate though it seems like the app service can't communicate with av service.
Is there anything else I need to do to be able to do that?
