### ISSUE TITLE
Error creating/updating service when only container port specified

### ISSUE THREAD

**Issue by bronislav** [aws/amazon-ecs-cli#1014]
#### Summary
Error "ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match" occurred during service create/update using compose style commands, if only container port specified.
 
#### Description
* Which specific command was run? 
Creating service using compose style command `ecs-cli compose service up`
* Which version of the CLI you are using?
```
❯ ecs-cli --version
ecs-cli version 1.18.1 (*UNKNOWN)
```
* Which version of Go are you using?
```
❯ go version
go version go1.14.2 darwin/amd64
```
* What platform are you using to run ECS CLI commands?
MacOS

#### Config files
* docker-compose.yml
```
version: '3'

services:
  api:
    image: <image_name>
    command: ./bin/start-api
    ports:
      - "9292"
    logging:
      driver: awslogs
      options:
        awslogs-group: log-group
        awslogs-region: eu-central-1
        awslogs-stream-prefix: "api"

```
* ecs-params.yml
```
version: 1

task_definition:
  task_execution_role: arn:aws:iam::692696475119:role/wlc-task-execution-role
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
  docker_volumes:
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-1"
        - "subnet-2"
        - "subnet-3"
      security_groups:
        - "sg-1"
      assign_public_ip: ENABLED
```
* ~/.ecs/config
```
version: v1
default: staging
clusters:
  staging:
    cluster: default
    region: eu-central-1
    default_launch_type: FARGATE
```
#### Expected Behavior
Service created and host port assigned dynamically.

#### Observed Behavior
```
ERRO[0000] Error registering task definition             error="ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match." family=service_name
ERRO[0000] Create task definition failed                 error="ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match."
FATA[0000] ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match.
```

I think this error occurred because port mappings being converted incorrectly. According to the converter code https://github.com/aws/amazon-ecs-cli/blob/3970a6c1f38bc750ff9c068f53220aa177c7df54/ecs-cli/modules/cli/compose/adapter/convert.go#L353 hostPort became 0 if not set in docker compose explicitly.
