### ISSUE TITLE
expose in docker-compose file doesn't work in ecs

### ISSUE THREAD

**Issue by ttj4** [aws/amazon-ecs-cli#1044]
#### Summary
I am trying to expose a port in docker-compose.yml ( I am not exposing the port in Dockerfile). Although this works locally, it doesn't seem to be working with ecs. I can see the service status as running in console.

#### Description

* Which specific command was run? 
`ecs-cli configure --cluster ${PROJECT} --region ${AWS_REGION} --default-launch-type FARGATE --config-name ${PROJECT}`
`ecs-cli up --cluster ${PROJECT} --force --security-group ${security_grp_id} --vpc ${vpc_id} --subnets ${subnet_ids}`
`ecs-cli compose --file docker-compose.yml --ecs-params params.ecs.yml --project-name ${PROJECT} service up --create-log-groups --cluster-config ${PROJECT}`

* Which version of the CLI you are using?
`ecs-cli version 1.19.0`
* Which version of Go are you using? 
`go version go1.12.9 darwin/amd64`
* What platform are you using to run ECS CLI commands? (E.g. Linux, macOS, Windows)
macOS

#### Config files

* docker-compose.yml
```
version: "3"
services:
    my-service:
        image: 12345678.dkr.ecr.us-west-2.amazonaws.com/my-service
        ports:
            - 5001:5001
        environment:
            - SERVICE_PORT=5001
        expose:
            - 5001
        logging:
            driver: awslogs
            options:
                awslogs-group: /ecs/test
                awslogs-region: us-west-2
                awslogs-stream-prefix: test
```

* ecs-params.yml
```
run_params:
  network_configuration:
    awsvpc_configuration:
      assign_public_ip: ENABLED
      security_groups:
      - sg-group
      subnets:
      - subnet-1
      - subnet-2
task_definition:
  ecs_network_mode: awsvpc
  services:
    my-service:
      essential: true
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 256
    mem_limit: 1GB
version: 1
```

* ~/.ecs/config
