### ISSUE TITLE
ecs-cli doesn't work with MFA - AssumeRoleTokenProviderNotSetError

### ISSUE THREAD

**Issue by habibcbly** [aws/amazon-ecs-cli#1057]
I got this error  :

```
Error executing 'up': AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

 when trying to execute this command :

 ```
ecs-cli up --force --capability-iam --size 2 --instance-type t2.medium --cluster-config [my-config] --aws-profile [my-profile] --port [xxxx] [xx]
```

With this configuration : 

* `.aws/config` 

```
[default]
region = eu-west-1

[profile my-profile]
role_arn = arn:aws:iam::xxxxxxxxxxx:role/xxxxxx
region = eu-west-1
source_profile = default
mfa_serial=arn:aws:iam::xxxxxxxxxx:mfa/xxxxxxxxxxx
```

* `.aws/credential` 
```
aws_access_key_id = XXXXXXXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
```

* `.ecs/config` 

```
version: v1
default: default
clusters:
  my-config:
    cluster: cluster_name
    region: eu-west-1
    default_launch_type: EC2
  default:
    cluster: default
    region: eu-west-1
    default_launch_type: EC2
```

* `.ecs/credential`

```
version: v1
default: my-profile
ecs_profiles:
  my-profile:
    aws_access_key_id: XXXXXXXXXXXXXXXXX
    aws_secret_access_key: XXXXXXXXXXXXXXXXXXXXXX
```

Also tried to use temporary session, but I got the same error. Thanks for help !
