### ISSUE TITLE
 Failed to resolve EFS

### ISSUE THREAD

**Issue by docktermj** [aws/amazon-ecs-cli#1083]
### Summary

When using `ecs-cli` to provision a task that mounts an EFS file system, the following error is returned:

> ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: Failed to resolve "fs-00000000.efs.us-east-1.amazonaws.com" - check that your file system ID is correct.

I did check.  The "file system ID" was correct.

### Description

To recreate, use the `hello-world.yaml` and `ecs-params.yaml` files described in **Config files** section below to run the following:

#### ecs-cli version

1. Show version.
   Example

    ```console
    $ ecs-cli --version
    ecs-cli version 1.20.0 (7547c45)
    ```

#### Configure ECS CLI

1. Configure `ecs-cli`.
   Example:

    ```console
    ecs-cli configure \
       --cluster hello-world-cluster \
       --config-name hello-world-config-name \
       --default-launch-type FARGATE \
       --region us-east-1
    ```

#### Create cluster

1. Create cluster.
   Example:

    ```console
    ecs-cli up \
      --cluster-config hello-world-config-name \
      --force
    ```

#### Save Cluster metadata

1. The `ecs-cli up` command that just completed prints metadata
   that needs to be captured in environment variables for later use.
   Example:

    ```console
    :
    INFO[0001] Waiting for your cluster resources to be created...
    INFO[0002] Cloudformation stack status         stackStatus=CREATE_IN_PROGRESS
    INFO[0063] Cloudformation stack status         stackStatus=CREATE_IN_PROGRESS
    VPC created: vpc-00000000000000000
    Subnet created: subnet-11111111111111111
    Subnet created: subnet-22222222222222222
    Cluster creation succeeded.
    ```

1. :pencil2: Set environment variable with VPC ID.
   Example:

    ```console
    export AWS_VPC_ID=vpc-00000000000000000
    ```

1. :pencil2: Set environment variable with Subnet #1
   Example:

    ```console
    export AWS_SUBNET_ID_1=subnet-11111111111111111
    ```

1. :pencil2: Set environment variable with Subnet #2
   Example:

    ```console
    export AWS_SUBNET_ID_2=subnet-22222222222222222
    ```

#### Find security group ID

1. Find AWS security group.
   Example:

    ```console
    export AWS_EC2_SECURITY_GROUP=$( \
      aws ec2 describe-security-groups \
        --filters Name=vpc-id,Values=${AWS_VPC_ID} \
        --region us-east-1 \
      | jq --raw-output ".SecurityGroups[0].GroupId"
    )
    ```

#### Open inbound ports

1. Open inbound ports.
   Example:

    ```console
    aws ec2 authorize-security-group-ingress \
      --group-id ${AWS_EC2_SECURITY_GROUP} \
      --ip-permissions \
        IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges='[{CidrIp=0.0.0.0/0,Description="SSH"}]'

    aws ec2 authorize-security-group-ingress \
      --group-id ${AWS_EC2_SECURITY_GROUP} \
      --ip-permissions \
        IpProtocol=tcp,FromPort=2049,ToPort=2049,IpRanges='[{CidrIp=0.0.0.0/0,Description="NFS"}]'
    ```

#### Provision Elastic File system

1. Create EFS file system.
   Example:

    ```console
    export AWS_EFS_FILESYSTEM_ID=$( \
      aws efs create-file-system \
        --creation-token hello-world-efs \
        --tags Key=Name,Value=hello-world-ecs-cluster-efs \
      | jq --raw-output ".FileSystemId"
    )
    ```

#### Run hello-world

1. Run task.
   Example:

    ```console
    ecs-cli compose \
      --cluster-config hello-world-config-name \
      --ecs-params ecs-params.yaml \
      --file hello-world.yaml \
      --project-name hello-world-project-name \
      up \
        --create-log-groups
    ```

#### hello-world.yaml

```yaml
version: '3'
services:
  helloworld:
    image: hello-world
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-world
        awslogs-region: us-east-1
        awslogs-stream-prefix: test
    user: "0"
    volumes:
      - hello-world:/opt/hello-world
volumes:
  hello-world:
```

#### ecs-params.yaml

```yaml
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 1GB
    cpu_limit: 256
  services:
    helloworld:
      cpu_shares: 0
      essential: true
      mem_limit: 2000000
  efs_volumes:
    - name: hello-world
      filesystem_id: ${AWS_EFS_FILESYSTEM_ID}
      root_directory: /hello-world
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - ${AWS_SUBNET_ID_1}
        - ${AWS_SUBNET_ID_2}
      security_groups:
        - ${AWS_EC2_SECURITY_GROUP}
      assign_public_ip: ENABLED
```

#### Expected Behavior

A successful mounting of the EFS file system onto the Docker container.

#### Observed Behavior

The actual error is seen in the AWS Console. (https://console.aws.amazon.com/ecs/home?#/clusters)

> ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: Failed to resolve "fs-00000000.efs.us-east-1.amazonaws.com" - check that your file system ID is correct.

```console
$ ecs-cli compose   --cluster-config hello-world-config-name   --ecs-params ecs-params.yaml   --file hello-world.yaml   --project-name hello-world-project-name   up     --create-log-groups

INFO[0000] Using ECS task definition                     TaskDefinition="hello-world-project-name:1"
INFO[0001] Created Log Group hello-world in us-east-1   
WARN[0001] Detected an EFS Volume in task definition arn:aws:ecs:us-east-1:000000000000:task-definition/hello-world-project-name:1 
WARN[0001] Using Fargate platform version 1.4.0, which includes changes to the networking flows for VPC endpoint customers. 
WARN[0001] Learn more: https://aws.amazon.com/blogs/containers/aws-fargate-launches-platform-version-1-4/ 
INFO[0002] Starting container...                         container=c492654b-0aae-4a5c-bed1-d963a02cb244/helloworld
INFO[0002] Describe ECS container status                 container=c492654b-0aae-4a5c-bed1-d963a02cb244/helloworld desiredStatus=RUNNING lastStatus=PROVISIONING taskDefinition="hello-world-project-name:1"
INFO[0014] Describe ECS container status                 container=c492654b-0aae-4a5c-bed1-d963a02cb244/helloworld desiredStatus=RUNNING lastStatus=PROVISIONING taskDefinition="hello-world-project-name:1"
INFO[0027] Describe ECS container status                 container=c492654b-0aae-4a5c-bed1-d963a02cb244/helloworld desiredStatus=STOPPED lastStatus=DEPROVISIONING taskDefinition="hello-world-project-name:1"
INFO[0039] Describe ECS container status                 container=c492654b-0aae-4a5c-bed1-d963a02cb244/helloworld desiredStatus=STOPPED lastStatus=DEPROVISIONING taskDefinition="hello-world-project-name:1"
INFO[0052] Stopped container...                          container=c492654b-0aae-4a5c-bed1-d963a02cb244/helloworld desiredStatus=STOPPED lastStatus=STOPPED taskDefinition="hello-world-project-name:1"
```

**Comment by docktermj** [comment]
I tried adding the following command and re-running `ecs-cli compose up`.  It gave the same error message.

```console
aws efs create-mount-target \
  --file-system-id ${AWS_EFS_FILESYSTEM_ID} \
  --subnet-id ${AWS_SUBNET_ID_1}
```

**Comment by docktermj** [comment]
@bvtujo As you recommended, I downloaded 1.20.0.  The above issue is my next blocker.   Am I just missing a configuration step?

Reference: https://github.com/aws/amazon-ecs-cli/issues/1043

**Comment by bvtujo** [comment]
Hmm, that's interesting. Can you try re-running the `create-mount-target` command, but this time specifying the security group?

```
aws efs create-mount-target \
  --file-system-id ${AWS_EFS_FILESYSTEM_ID} \
  --subnet-id ${AWS_SUBNET_ID_1} \
  --security-groups ${AWS_EC2_SECURITY_GROUP}
```

This is one of the configuration steps that's done when creating an EFS filesystem through the console and was a part of our testing. It associates the Network Interface which is created with the provided security group [1], and you've opened up SSH and NFS access in that SG.

[1] https://docs.aws.amazon.com/cli/latest/reference/efs/create-mount-target.html

**Comment by docktermj** [comment]
@bvtujo I tried your suggestion but still get the same error:

> ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: Failed to resolve "fs-00000000.efs.us-east-1.amazonaws.com" - check that your file system ID is correct.

**Comment by docktermj** [comment]
I'm using the updated instructions seen at https://github.com/Senzing/docker-compose-aws-ecscli-demo/tree/79a3d8a55d20b59371a60bca81b29e88e3b357eb/debug/efs

**Comment by bvtujo** [comment]
Hi @docktermj, I've dug a little more into this to see if I could get a working example. 

I was eventually able to get a task running using an EFS volume I created through the console, with mount points in both subnets created by `ecs-cli up` and the following additional configurations: 

```bash
ecs-cli compose \
  --ecs-params ecs-params.yml \
  --file docker-compose.yml \
  up \
  --cluster-config -fargate-tutorial-config \
  --create-log-groups
```

#### ecs-params.yml
```yml
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 1.0GB
    cpu_limit: 512
  efs_volumes:
    - name: myEFSVolume
      filesystem_id: fs-000000
      root_directory: /
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-0000000000000000
        - subnet-0000000000000000
      security_groups:
        - sg-00000000000000
      assign_public_ip: ENABLED
```

#### docker-compose.yml
```yml
version: '3'
services:
  web:
    image: 000000000000.dkr.ecr.us-west-2.amazonaws.com/hello:latest
    volumes:
      - myEFSVolume:/mount/efs
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-group: hello
        awslogs-region: us-west-2
        awslogs-stream-prefix: web
volumes:
  myEFSVolume:
```

The main differences I can see between my config and yours are: 
1. The EFS file system has mount points in both VPC subnets. 
2. I'm using the root of the filesystem. When I tried to run a task using a directory which didn't yet exist in the FS, I also got an error:
```bash
ResourceInitializationError: failed to invoke EFS utils commands to set up EFS volumes: stderr: mount.nfs4: mounting fs-0000000.efs.us-west-2.amazonaws.com:/hello-world failed, reason given by server: No such file or directory : unsuccessful EFS utils...
```
3. I'm using ECR for my image. 
4. (incredibly minor) I've specified the cluster config after "up," but I don't believe that matters. 

The security group is "fresh," including only the default inbound and outbound rules. This is all running in us-west-2.  

Please let me know if this is helpful.

**Comment by docktermj** [comment]
@bvtujo   I'm continuing to research this.  I have gotten it to work with an AWS Console created EFS and am figuring out what the difference is between that and an `aws efs create-file-system` EFS instance is.   At the moment it centers around the security group.   Will post more as I find more.

**Comment by bvtujo** [comment]
Thanks for keeping us updated. I'd suggest creating mount points with `aws efs create-mount-point` in *both* subnets output by `ecs-cli up`, taking care to specify the security group you found above as a flag (`--security-groups ${AWS_EC2_SECURITY_GROUP`). 

You may also be interested in the ongoing [Docker Compose work](https://aws.amazon.com/blogs/containers/aws-and-docker-collaborate-to-simplify-the-developer-experience/) we just announced yesterday, which is a direct integration between docker compose and ECS and is set to take over many of the functions of the ecs-cli.

**Comment by docktermj** [comment]
@bvtujo  It appears that there is a bug somewhere in the `aws` command or `ecs-cli` command when it comes to security group inbound rules.

The following instructions show a bug where a security group inbound rule needs to be created (via `aws ec2 authorize-security-group-ingress`) then deleted from the AWS console for the EFS to mount.  So there is a behaviorial difference between the AWS console and command line invocations. That is: something is being done in the AWS Console that is not being done in command-line invocation.

From what I can tell there's a bug in either `aws` or `ecs-cli` that prevents proper use of security group inbound rules.   In other words, without ever using the AWS Console, try to provision an EFS instance and use it with an `ecs-cli` provisioned ECS FARGATE task.  Try as I might, it doesn't work.

To recreate, use the `hello-world.yaml` and `ecs-params.yaml` files described in **Config files** section below to run the following:

### ecs-cli version

1. Show version.
   Example

    ```console
    $ ecs-cli --version
    ecs-cli version 1.20.0 (7547c45)
    ```

### Variables

1. :pencil2: Unique name for test.
   Example:

    ```console
    export AWS_PROJECT=test01
    ```

1. Synthesize variables.
   Example:

    ```console
    export AWS_CLUSTER=${AWS_PROJECT}-hello-world-cluster
    export AWS_CONFIG_NAME=${AWS_PROJECT}-hello-world-config-name
    ```

### Configure ECS CLI

1. Configure `ecs-cli`.
   Example:

    ```console
    ecs-cli configure \
       --cluster ${AWS_CLUSTER} \
       --config-name ${AWS_CONFIG_NAME} \
       --default-launch-type FARGATE \
       --region us-east-1
    ```

### Create cluster

1. Create cluster.
   Example:

    ```console
    ecs-cli up \
      --cluster-config ${AWS_CONFIG_NAME} \
      --force
    ```

### Save Cluster metadata

1. The `ecs-cli up` command that just completed prints metadata
   that needs to be captured in environment variables for later use.
   Example:

    ```console
    :
    INFO[0001] Waiting for your cluster resources to be created...
    INFO[0002] Cloudformation stack status         stackStatus=CREATE_IN_PROGRESS
    INFO[0063] Cloudformation stack status         stackStatus=CREATE_IN_PROGRESS
    VPC created: vpc-00000000000000000
    Subnet created: subnet-11111111111111111
    Subnet created: subnet-22222222222222222
    Cluster creation succeeded.
    ```

1. :pencil2: Set environment variable with VPC ID.
   Example:

    ```console
    export AWS_VPC_ID=vpc-00000000000000000
    ```

1. :pencil2: Set environment variable with Subnet #1.
   Example:

    ```console
    export AWS_SUBNET_ID_1=subnet-11111111111111111
    ```

1. :pencil2: Set environment variable with Subnet #2.
   Example:

    ```console
    export AWS_SUBNET_ID_2=subnet-22222222222222222
    ```

### Find security group ID

1. Find AWS security group.
   Example:

    ```console
    export AWS_EC2_SECURITY_GROUP=$( \
      aws ec2 describe-security-groups \
        --filters Name=vpc-id,Values=${AWS_VPC_ID} \
        --region us-east-1 \
      | jq --raw-output ".SecurityGroups[0].GroupId"
    )
    ```

### Provision Elastic File system

1. Create EFS file system.
   Example:

    ```console
    export AWS_EFS_FILESYSTEM_ID=$( \
      aws efs create-file-system \
        --creation-token hello-world-efs \
        --tags Key=Name,Value=${AWS_CLUSTER}-efs \
      | jq --raw-output ".FileSystemId"
    )
    ```

### Create EFS mounts

1. Create mount in first subnet.
   Example:

    ```console
    aws efs create-mount-target \
      --file-system-id ${AWS_EFS_FILESYSTEM_ID} \
      --security-groups ${AWS_EC2_SECURITY_GROUP} \
      --subnet-id ${AWS_SUBNET_ID_1}
    ```

1. Create mount in second subnet.
   Example:

    ```console
    aws efs create-mount-target \
      --file-system-id ${AWS_EFS_FILESYSTEM_ID} \
      --security-groups ${AWS_EC2_SECURITY_GROUP} \
      --subnet-id ${AWS_SUBNET_ID_2}
    ```

### Open inbound ports

1. Open inbound ports.
   Example:

    ```console
    aws ec2 authorize-security-group-ingress \
      --group-id ${AWS_EC2_SECURITY_GROUP} \
      --ip-permissions \
        IpProtocol=tcp,FromPort=2049,ToPort=2049,IpRanges='[{CidrIp=0.0.0.0/0,Description="NFS"}]'
    ```

### Run hello-world

1. Run task.
   Example:

    ```console
    ecs-cli compose \
      --cluster-config ${AWS_CONFIG_NAME} \
      --ecs-params ecs-params.yaml \
      --file hello-world.yaml \
      --project-name ${AWS_PROJECT}-project-1 \
      up \
        --create-log-groups
    ```

1. **Result:**  Failure

### Delete inbound rule

1. Visit AWS console for [Security Groups](https://console.aws.amazon.com/ec2/v2/home?#SecurityGroups:)
1. Choose security group.
1. In "Inbound rules" section, click "Edit inbound rules" button.
1. Delete "NFS" inbound rule.
1. Click "Save rules" button

### Second run hello-world

1. Run task.
   Example:

    ```console
    ecs-cli compose \
      --cluster-config ${AWS_CONFIG_NAME} \
      --ecs-params ecs-params.yaml \
      --file hello-world.yaml \
      --project-name ${AWS_PROJECT}-project-2 \
      up \
        --create-log-groups
    ```

1. **Result:**  Success

### Config files

#### hello-world.yaml

```yaml
version: '3'
services:
  helloworld:
    image: senzing/hello-world-on-hub-docker-com
    logging:
      driver: awslogs
      options:
        awslogs-group: hello-world
        awslogs-region: us-east-1
        awslogs-stream-prefix: test
    user: "0"
    volumes:
      - hello-world:/opt/hello-world
volumes:
  hello-world:
```

#### ecs-params.yaml

```yaml
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 1GB
    cpu_limit: 512
  efs_volumes:
    - name: hello-world
      filesystem_id: ${AWS_EFS_FILESYSTEM_ID}
      root_directory: /
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - ${AWS_SUBNET_ID_1}
        - ${AWS_SUBNET_ID_2}
      security_groups:
        - ${AWS_EC2_SECURITY_GROUP}
      assign_public_ip: ENABLED
```

**Comment by bvtujo** [comment]
Hi @docktermj, I was able to get a container running via an EFS file system created with the AWS CLI (albeit an older release of version 1) with the following steps:
```bash
$ aws --version
aws-cli/1.17.16 Python/3.7.3 Darwin/18.7.0 botocore/1.14.16
```
### Create file system
```
export AWS_EFS_FILESYSTEM_ID=$( \
  aws efs create-file-system \
    --creation-token hello-world-efs \
    --no-encrypt \
    --throughput-mode bursting \
    --performance-mode generalPurpose \
    --region us-west-2 \
    | jq --raw-output ".FileSystemId"
)
```
### Create mount targets
```
aws efs create-mount-target \
  --file-system-id ${AWS_EFS_FILESYSTEM_ID} \
  --security-groups ${AWS_EC2_SECURITY_GROUP} \
  --subnet-id ${AWS_SUBNET_ID_1}

aws efs create-mount-target \
  --file-system-id ${AWS_EFS_FILESYSTEM_ID} \
  --security-groups ${AWS_EC2_SECURITY_GROUP} \
  --subnet-id ${AWS_SUBNET_ID_2}
```

### Deploy cluster
```
./ecs-cli compose \
  --ecs-params ecs-params.yml \
  --file docker-compose.yml \
  --cluster-config my-config \
  up \
  --create-log-groups
```

#### ecs-params.yml
```
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 1.0GB
    cpu_limit: 512
  efs_volumes:
    - name: myEFSVolume
      filesystem_id: fs-0123456
      root_directory: /
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-0000000000000000
        - subnet-0000000000000001
      security_groups:
        - sg-0000000000000000
      assign_public_ip: ENABLED
```

#### docker-compose.yml
```
version: '3'
services:
  web:
    image: 00000000000.dkr.ecr.us-west-2.amazonaws.com/helloworld:latest
    volumes:
      - myEFSVolume:/mount/efs
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: otter
        awslogs-region: us-west-2
        awslogs-stream-prefix: web
volumes:
  myEFSVolume:
```

#### Security group description 
```
$ aws ec2 describe-security-groups --group-id ${AWS_EC2_SECURITY_GROUP}
{
    "SecurityGroups": [
        {
            "Description": "default VPC security group",
            "GroupName": "default",
            "IpPermissions": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": [
                        {
                            "GroupId": "sg-000000000000000",
                            "UserId": "123456789012"
                        }
                    ]
                }
            ],
            "OwnerId": "123456789012",
            "GroupId": "sg-000000000000000",
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1",
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "Ipv6Ranges": [],
                    "PrefixListIds": [],
                    "UserIdGroupPairs": []
                }
            ],
            "VpcId": "vpc-00000000000000"
        }
    ]
}
```
