### ISSUE TITLE
ecs-cli parses YAML environment settings more stringently than docker-compose

### ISSUE THREAD

**Issue by markriggins** [aws/amazon-ecs-cli#109]
This works for `docker-compose`:
```
mysql:
  image: mysql:5.6
  environment:
    MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    MYSQL_DATABASE: 'my_db'
    MYSQL_USER: 'my_user'
    MYSQL_PASSWORD: 'password'

```
but ecs-cli preserves the quotes and tries to use `'password'` as the password, not `password`.
Regardless of which of these is correct, yaml files that are accepted by `docker-compose` should work for `ecs-cli`.

For ecs-cli we removed the quotes.  This is not a major issue, but while you're cleaning up the other yaml parsing problems, you might as well get this one too.

This alternative form works properly with ecs-cli:
```
mysql:
  image: mysql:5.6
  environment:
    -MYSQL_RANDOM_ROOT_PASSWORD=yes
    -MYSQL_DATABASE=my_db
    -MYSQL_USER=my_user
    -MYSQL_PASSWORD=password

```
but I haven't tried it with colons, commas or spaces in the password.
