### ISSUE TITLE
supply secretOptions to logConfiguration

### ISSUE THREAD

**Issue by bpottier** [aws/amazon-ecs-cli#1093]
Unless I'm wrong, there doesn't seem to be any way to supply secretOptions to the log configuration for a container.

Ideally I would be able to add a secret option like this:

docker-compose.yml
```
service:
  logging:
    options:
      foo: bar
```

ecs-params.yml
```
service:
  secret_options:
    - name: secret
      value_from: secret_value
```

Am I missing something, or is this currently not possible?

**Comment by bpottier** [comment]
I figured it out.

in ecs-params.yml you can supply a "logging" key, which isn't documented so far as I could find.

```
logging:
  secret_options:
    - name: name
      value_from: secret_arn
```
