### ISSUE TITLE
secret_options in ecs-params.yml

### ISSUE THREAD

**Issue by bpottier** [aws/amazon-ecs-cli#1094]
secretOptions is null when creating a task definition.

I originally created this as a feature request, but I realize you do support this functionality, it just isn't working. See: https://github.com/aws/amazon-ecs-cli/issues/1093

Version: 1.20.0
OS: macOS
Command: ecs-cli compose create --launch-type FARGATE

```
  services:
    service:
      essential: true
      secret_options:
        - name: apikey
          value_from: <secret_arn>
```

When I create the task definition I still get a null value for secretOptions, but I don't get any errors when generating the task definition.
