### ISSUE TITLE
Error attempting to ecs-cli compose up

### ISSUE THREAD

**Issue by nathanleclaire** [aws/amazon-ecs-cli#11]
Created a cluster running on two instances like specified in the examples.

This is my compose file (`docker-compose-prod.yml`):

``` yaml
web:
    image: nathanleclaire/laraveldocker_web
    links:
     - db
     - redis
     - beanstalkd
    ports:
     - "80:80"
    volumes:
     - /var/lib/lightning/mysql:/var/lib/lightning/mysql
db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
    volumes:
     - /var/lib/mysql
redis:
    image: redis
beanstalkd:
    image: nathanleclaire/laraveldocker_beanstalkd
```

When I run:

``` console
$ ecs-cli compose -f docker-compose-prod.yml up
ERRO[0000] Error registering task definition             error=ClientException: host.sourcePath should not be blank.
        status code: 400, request id: b7a2c30b-6e0f-11e5-a4a1-6b2efea4c01d family=0x820c5e110
ERRO[0000] Create task definition failed                 error=ClientException: host.sourcePath should not be blank.
        status code: 400, request id: b7a2c30b-6e0f-11e5-a4a1-6b2efea4c01d
FATA[0000] ClientException: host.sourcePath should not be blank.
        status code: 400, request id: b7a2c30b-6e0f-11e5-a4a1-6b2efea4c01d
```

Seems that `sourcePath` is not getting set as it should be in the task definition.

**Comment by PLEEROCK** [comment]
Have the same problem with even such a simple configuration:
```yml
data-container:
  image: mongo:3.1.9
  volumes:
    - /data/db
```
looks like volumes are not working at all? When this gonna be fixed, and is there a temporary solution for now?

**Comment by previa** [comment]
```
mysql:
  build: .
  command: /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306 --bind-address=0.0.0.0
  # https://github.com/docker-library/mysql/blob/master/5.6/Dockerfile
  ports:
   - "3306:3306"
solr:
  build: .
  working_dir: /root/solr/example/
  command: java -jar start.jar
  ports:
   - "8984:8984"
ui:
  build: .
  working_dir: /root/insurance_ui/
  command: python httpd.py
  ports:
   - "9090:9090"
api:
  build: .
  working_dir: /root/insurance_api/
  command:  python manage.py runserver 0.0.0.0:7000
  ports:
   - "7000:7000"
  links:
   - mysql:mysql
   - solr:solr
```

```
➜  ecs  ./ecs-cli compose -f docker-compose.yml up
WARN[0000] Skipping unsupported YAML option...           option name=build
WARN[0000] Skipping unsupported YAML option...           option name=working_dir
WARN[0000] Skipping unsupported YAML option...           option name=build
WARN[0000] Skipping unsupported YAML option...           option name=working_dir
WARN[0000] Skipping unsupported YAML option...           option name=build
WARN[0000] Skipping unsupported YAML option...           option name=working_dir
WARN[0000] Skipping unsupported YAML option...           option name=build
ERRO[0000] Error registering task definition             error=ClientException: Container.image should not be null or empty.
	status code: 400, request id: 61061f57-9361-11e5-b7e7-99c8fdd92fa9 family=0xc2080bf640
ERRO[0000] Create task definition failed                 error=ClientException: Container.image should not be null or empty.
	status code: 400, request id: 61061f57-9361-11e5-b7e7-99c8fdd92fa9
FATA[0000] ClientException: Container.image should not be null or empty.
	status code: 400, request id: 61061f57-9361-11e5-b7e7-99c8fdd92fa9
```

**Comment by uttarasridhar** [comment]
@previa, the build option is not supported at the moment, you will have to supply the image name.

**Comment by Korri** [comment]
Any news on `ClientException: host.sourcePath should not be blank` I need a volume to share between my instances, but I don't want it to be persistent.

**Comment by Nyholm** [comment]
I do also face this problem.

**Comment by philipn** [comment]
FYI, a workaround here:

Just use `VOLUME` at the end of your relevant `Dockerfile`.  This will do what you want.  Then remove the non-host-specific `volume` entry from your `docker-compose.yml` file.

**Comment by aventurella** [comment]
:+1: for this as well. It would be nice to be able to use `volumes` in the compose file or at LEAST provide a better error that it fails because of volumes.

**Comment by seanknox** [comment]
Hi @uttarasridhar has there been any movement on this issue?

**Comment by benfortuna** [comment]
FYI, another workaround if you don't have access to modify the Dockerfile:

Specify the host path explicitly, even if it is the same as the source path. e.g.

```
data:
  image: tianon/true
  volumes:
   - /opt/data:/opt/data
```
