### ISSUE TITLE
compose service up ignores --launch-type?

### ISSUE THREAD

**Issue by mlooney** [aws/amazon-ecs-cli#1106]
ecs-cli service up seems to ignore the --launch-type flag

#### Summary
I have a cluster with a default launch type of FARGATE, but wish to deploy a task of type EC2

```
 ecs-cli compose  --project-name worker --ecs-params worker-params.yml service up --launch-type EC2 --force-deployment --cluster clustername
```

The task deploys fine, but the launch type displayed in the console remains FARGATE

#### Description

command:
``` ecs-cli compose  --project-name worker --ecs-params worker-params.yml service up --launch-type EC2 --force-deployment --cluster clustername```
* Which version of the CLI you are using? (Run: `ecs-cli --version`)
* Which version of Go are you using? (Run: `go version`)
* What platform are you using to run ECS CLI commands? (E.g. Linux, macOS, Windows)

ecs-cli 1.20.0

#### Config files

ecs-params:

```
version: 1    
task_definition:    
  task_execution_role: ecsTaskExecutionRole    
  ecs_network_mode: awsvpc    
  task_size:    
    mem_limit: 8GB    
    cpu_limit: 2048    
run_params:    
  network_configuration:    
    awsvpc_configuration:    
      subnets:    
        - "subnet-x"    
        - "subnet-x"    
      security_groups:    
        - "sg-x"    
      assign_public_ip: ENABLED    
  service_discovery:    
    private_dns_namespace:    
      name: cluster    
      vpc: "vpc-x"
```

no ~/.ecs/config

#### Expected Behavior
Deploy an ec2-type task

#### Observed Behavior
deploys a margate-type task
