### ISSUE TITLE
ECS-CLI remembers old Target group ARN, refuses to take the new TG ARN

### ISSUE THREAD

**Issue by SongGithub** [aws/amazon-ecs-cli#1108]
#### Summary

after replaced Target group with Terraform, and running ECSCLI. The CLI prompts error "the old Target group not exist"

#### Description

* Which specific command was run? (Example: `ecs-cli up --capability-iam --size 2 --launch-type EC2`)
```
/usr/local/bin/ecs-cli compose \
  --file /deploy/docker-compose.yml \
  --project-name test-tooling \
  --ecs-params /deploy/ecs-params.yml \
  --region ap-southeast-2 \
  --cluster ecs-cluster service up \
  --timeout 8 --create-log-groups \
  --target-group-arn arn:aws:elasticloadbalancing:ap-southeast-2:<THE NEW TG ARN> --container-name nginx --container-port 443
```
* Which version of the CLI you are using? (Run: `ecs-cli --version`)
ecs-cli version 1.20.0 (7547c45)
* Which version of Go are you using? (Run: `go version`) 
NA
* What platform are you using to run ECS CLI commands? (E.g. Linux, macOS, Windows)
LINUX 

#### Config files

* docker-compose.yml

* ecs-params.yml
```
version: 1
task_definition:
  task_execution_role: ${EXECUTION_ROLE_ARN}
  services:
      nginx:
        mem_reservation: 128m
      express:
        mem_reservation: 128m
```

* ~/.ecs/config

#### Expected Behavior
ECSCLI takes the new TG, and deploy normally.

#### Observed Behavior
ECSCLI remembers the deleted old TG ARN, and complains that it is missing, refuses to take the newly given TG ARN.
