### ISSUE TITLE
.env file variables are not interpolated into docker-compose.yaml when using `docker compose`

### ISSUE THREAD

**Issue by AttilaTheFun** [aws/amazon-ecs-cli#1137]
I'm trying to migrate my `docker-compose` v1 application from DigitalOcean to AWS with the new `docker compose` v2 system using an ECS context.

I can run `docker compose --env-file .env config` with the default context and verify that the parameters are interpolated correctly, but when I switch to an ECS context, this stops working.

docker-compose.yaml:
```
version: "3"
services:
  web:
    container_name: web
    image: ${DOCKER_REGISTRY}/web:latest
```

.env:
```
DOCKER_REGISTRY=example.com
```

The ECS context *can* read + interpolate exported environment variables from the shell, but not the .env file.

If this is by design, it should not fail silently and should throw an error saying this feature of docker compose is not supported. Otherwise, this should be tracked as a bug.
