### ISSUE TITLE
when I run a task locally it does not seem to pickup environment variable containing values from parameterstore

### ISSUE THREAD

**Issue by tkumark** [aws/amazon-ecs-cli#1155]
#### Summary
I am running the following command 
ecs-cli local up --task-def-remote app-main:6
my taskdefinition contains environment variables which referes values in parameter store. When it runs locally it does not seem to pull those values from parameter store .

Is there anything missing or extra step I should be following?

docker-compose.ecs-local.yml
```
version: "3.4"
services:
  test-docker-env:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      CERT_ANDROID_P12: ${test-docker-env_CERT_ANDROID_ETUDIER_P12}
      CERT_ANDROID: ${test-docker-env_CERT_ANDROID_STUDYMODE}
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: 1234556677.dkr.ecr.us-east-1.amazonaws.com/test-docker-env:latest
    labels:
      ecs-local.secret.CERT_ANDROID_P12: arn:aws:ssm:us-east-1:1234556677:parameter/Dev/myparameter
      ecs-local.secret.CERT_ANDROID: arn:aws:ssm:us-east-1:1234556677:parameter/Dev/myparameter2
      ecs-local.task-definition-input.type: remote
      ecs-local.task-definition-input.value: test-docker-env:1
    networks:
      ecs-local-network: null
    ports:
    - target: 80
      published: 80
      protocol: tcp
networks:
  ecs-local-network:
    external: true
```
