### ISSUE TITLE
Wrong line for yml parser error "while scanning a simple key"

### ISSUE THREAD

**Issue by ecejas** [aws/amazon-ecs-cli#134]
Hi, @uttarasridhar 

By running this:

> $ecs-cli compose --file prod.yml up

I get error:

> ERRO[0000] Could not parse config for project axe : yaml: [while scanning a simple key] could not find expected ':' at line 13, column 5 
ERRO[0000] Unable to open ECS Compose Project            error=yaml: [while scanning a simple key] could not find expected ':' at line 13, column 5
FATA[0000] Unable to create and read ECS Compose Project  error=yaml: [while scanning a simple key] could not find expected ':' at line 13, column 5

yml doc:

```yaml
# This file is for local development.
# TODO: Migrate to version 2
version: '2'
services:
  data:
    image: tianon/true
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql

  db:
    restart: always
    image:postgres
    volumes_from:
      - data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    depends_on:
      - data   
```

But the error its not really in line 13, its in line 12. This is a linter/parser error possibly. 

Try to run it here: http://www.yamllint.com/

The error should say line 12, not 13.

Can you tell me how to put my yml in a nice format to be seen here?

**Comment by uttarasridhar** [comment]
Thanks for the bug report. We use a third party library for parsing the yaml file.

Can i take a look at your prod.yml compose file so i can debug it better.

**Comment by ecejas** [comment]
@uttarasridhar Sorry, updated the issue with the yml doc.

**Comment by uttarasridhar** [comment]
Thanks for yml file. You can use the markdown format for [syntax highlighting](https://guides.github.com/features/mastering-markdown/) and use ```yaml

**Comment by ecejas** [comment]
Thanks!

**Comment by uttarasridhar** [comment]
[Yaml Spec](http://www.yaml.org/spec/1.2/spec.html#id2759963): 'Mappings use a colon and space (“: ”) to mark each key: value pair.'

For the option: `image:postgres`, change it to "image: postgres"

**Comment by uttarasridhar** [comment]
Ah, I see what you mean. Thanks for reporting this.

**Comment by ecejas** [comment]
Correct. I just wanted to point out that the output error message points to the wrong line. :)

**Comment by uttarasridhar** [comment]
fixed by migrating to latest libcompose (which now depends on go-yaml) https://github.com/aws/amazon-ecs-cli/pull/158

**Comment by aage21** [comment]
Mb

**Comment by hovermind** [comment]
In my case ':' was missing in yaml (human error)

```
parameters:
- name: 'command'
  type: string
  default: 'up'

steps: # ':' was missing here
- script: echo "xyz"
```
