### ISSUE TITLE
Workaround for unsupported  'expose' command

### ISSUE THREAD

**Issue by ecejas** [aws/amazon-ecs-cli#135]
Hi @uttarasridhar , 

A workaround for missing support for yml option expose?

Context:
I am using this yml for creating a task definition:

``` yaml
# This file is for production development.
version: '2'
services:
  data:
    image: tianon/true
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
    mem_limit: 124288000

  db:
    #restart: always
    image: postgres
    volumes_from:
      - data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    #depends_on:
    #  - data
    mem_limit: 124288000

  web:
    #restart: always
    image: cejas/web
    #expose:
    #  - "8000"
    ports:
        - "8000:8000"
    volumes:
      - /code:/code
    env_file:
      - ./env-vars/base.env
      - ./env-vars/base-secrets.env
      - ./env-vars/local.env
      - ./env-vars/local-secrets.env
    command: ["uwsgi", "--ini", "/code/uwsgi/axe.ini", "--uid", "www-data", "--gid", "www-data", "--env", "DJANGO_SETTINGS_MODULE=axe.settings.local"]
    mem_limit: 124288000

# Nginx
  nginx:
    #restart: always
    image: cejas/nginx
    volumes_from:
        - web
    ports:
        - "80:80"
    links:
    - web:web
    mem_limit: 124288000
```

The task definition gets created but stops immediately after the 'web' exits with status code 1.

![screen shot 2016-07-17 at 5 57 06 pm](https://cloud.githubusercontent.com/assets/15933097/16904298/ff9879d6-4c47-11e6-8099-42a3f0adb0e2.png)

I suspects hast to do by missing the 'expose' command?
Any way I could troubleshoot this better?

Thanks!
