### ISSUE TITLE
Getting error: panic: interface conversion: interface is string, not []interface {}

### ISSUE THREAD

**Issue by mehmeta** [aws/amazon-ecs-cli#138]
I'm getting the following error:

ecs-cli compose --file docker-compose.yml up
panic: interface conversion: interface is string, not []interface {}

goroutine 1 [running]:
panic(0xb32c00, 0xc82015fcc0)
    /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.readEnvFile(0x7ff199e06130, 0x110b198, 0xc82015b200, 0x12, 0xc820159cb0, 0x7, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge.go:89 +0x161
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.parseV2(0x7ff199e06130, 0x110b198, 0x7ff199e06108, 0xc82015b620, 0xc82015b200, 0x12, 0xc820159cb0, 0xc820159c50, 0x10e46e0, 0xc82001a0c0, ...)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge_v2.go:95 +0x83
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.MergeServicesV2(0xc82015b660, 0x7ff199e06108, 0xc82015b620, 0x7ff199e06130, 0x110b198, 0xc82015b200, 0x12, 0xc820145400, 0x752, 0x952, ...)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge_v2.go:36 +0x2e3
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config.Merge(0xc82015b660, 0x7ff199e06108, 0xc82015b620, 0x7ff199e06130, 0x110b198, 0xc82015b200, 0x12, 0xc820145400, 0x752, 0x952, ...)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/config/merge.go:40 +0x24c
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(_Project).load(0xc82015da00, 0xc82015b200, 0x12, 0xc820145400, 0x752, 0x952, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:159 +0xdf
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project.(_Project).Parse(0xc82015da00, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/docker/libcompose/project/project.go:84 +0x323
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(_ecsProject).parseCompose(0xc82015da00, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:116 +0xfd
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs.(_ecsProject).Parse(0xc82015da00, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/ecs/project.go:105 +0xde
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.loadProject(0x7ff199e06248, 0xc82015da00, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:101 +0x33
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.projectFactory.Create(0xc82016e1e0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/factory.go:50 +0xe6
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.(_projectFactory).Create(0x110b198, 0xc82016e1e0, 0xc820139e00, 0x0, 0x0, 0x0, 0x0)
    <autogenerated>:2 +0xb8
github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app.WithProject.func1(0xc82016e1e0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/compose/cli/ecs/app/app.go:45 +0x6a
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xc37068, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xdcd0e0, 0xac, 0x0, ...)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:127 +0x1055
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(_App).RunAsSubcommand(0xc8200acd00, 0xc82016e000, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:257 +0xdac
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.startApp(0xc34238, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd52b40, 0x39, 0x0, ...)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:199 +0x74a
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.Command.Run(0xc34238, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd52b40, 0x39, 0x0, ...)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/command.go:55 +0x15f3
github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli.(*App).Run(0xc8200acb00, 0xc82000a050, 0x5, 0x5, 0x0, 0x0)
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/github.com/codegangsta/cli/app.go:159 +0xc34
main.main()
    /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0x9fa

Below is the docker-compose.yml

``` yaml
version: '2'

services:
  postgres:
    image: myrepo.dkr.ecr.us-west-2.amazonaws.com/myrepo:postgres-d980b0f1a9b07eeefe6ebf70df3c5238a62dfb24

    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - /backups:/backups
    env_file: .env

  django:
    image: myrepo.dkr.ecr.us-west-2.amazonaws.com/myrepo:django-d980b0f1a9b07eeefe6ebf70df3c5238a62dfb24
    user: django
    depends_on:
      - postgres
      - redis
    command: /gunicorn.sh
    env_file: .env

  nginx:
    image: myrepo.dkr.ecr.us-west-2.amazonaws.com/myrepo:nginx-d980b0f1a9b07eeefe6ebf70df3c5238a62dfb24
    depends_on:
      - django
      - certbot
    ports:
      - "0.0.0.0:80:80"
    environment:
      - MY_DOMAIN_NAME=myrepo.com
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: squay.io/letsencrypt/letsencrypt
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d myrepo.com --text --agree-tos --email myrepo@myrepo.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --standalone-supported-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm

  redis:
    image: sredis:latest
```
