### ISSUE TITLE
CannotCreateContainerError: API error (500): expected integer

### ISSUE THREAD

**Issue by ecejas** [aws/amazon-ecs-cli#141]
Hi @uttarasridhar  ,

I need help to debug an error I am getting when launching my service.
running this command:

``` bash
$ ecs-cli compose -f prod.yml up
```

My containers stop and I get this:

![screen shot 2016-07-27 at 1 20 46 am](https://cloud.githubusercontent.com/assets/15933097/17168693/a310e894-5398-11e6-976c-87a3fec018f6.png)

prod.yml looks like this:

``` yaml
# This file is for production development.
version: '2'
services:
  web:
    #restart: always
    image: cejas/web
    #expose:
    #  - "8000"
    ports:
        - "8000:8000"
    #volumes:
    #  - /code:/code
    env_file:
      - ./env-vars/base.env
      - ./env-vars/base-secrets.env
      - ./env-vars/production.env
      - ./env-vars/production-secrets.env
    command: ["uwsgi", "--ini", "/code/uwsgi/axe.ini", "--uid", "www-data", "--gid", "www-data", "--env", "DJANGO_SETTINGS_MODULE=axe.settings.production"]
    mem_limit: 209715200

# Nginx
  nginx:
    #restart: always
    image: cejas/nginx
    volumes_from:
        - web
    ports:
        - "80:80"
    links:
    - web:web
    mem_limit: 209715200
```

I this "Expected integer error" from the image? Even if I comment everything in the yml file I would still get this error. How can I debug this?

Thanks!
