### ISSUE TITLE
log_driver during compose

### ISSUE THREAD

**Issue by mkoppanen** [aws/amazon-ecs-cli#162]
Am I missing something or is log_driver and log_opt dropped from the output? Running with following yaml file:

```
version: '2'
services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
     - "80:80"
    log_driver: awslogs
    log_opt:
     aws-region: us-west-2
```

Produces following output (ecs-cli compose -f <file> --debug up):

```
  ContainerDefinitions: [{
      Command: [],
      Cpu: 0,
      DnsSearchDomains: [],
      DnsServers: [],
      DockerLabels: {

      },
      DockerSecurityOptions: [],
      EntryPoint: [],
      Environment: [],
      ExtraHosts: [],
      Image: "amazon/amazon-ecs-sample",
      Links: [],
      Memory: 512,
      MountPoints: [],
      Name: "web",
      PortMappings: [{
          ContainerPort: 80,
          HostPort: 80,
          Protocol: "tcp"
        }],
      Privileged: false,
      ReadonlyRootFilesystem: false,
      Ulimits: [],
      VolumesFrom: []
    }],
  Family: "ecs-cli-test",
  Volumes: []
}
```

**Comment by yinshiua** [comment]
Version 2 file format no longer accepts `log_driver` and `log_opt`. See https://docs.docker.com/compose/compose-file/#/logging for reference.

We are working on better error handling. (Pending release)

**Comment by mtomas** [comment]
any updates on this ?

**Comment by uttarasridhar** [comment]
Released in https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.5

**Comment by garthk** [comment]
For those coming here via Google in early-mid 2017:

Contrary to @yinshiua's advice above, the `docker-compose.yml` version 2 format does accept `log_driver` and `log_opt`. It's version 3 that replaces them with `logging.driver` and `logging.options`.

Contrary to the [ECS CLI tutorial](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html#ECS_CLI_tutorial_compose_create), which as of writing says…

> At this time, the Amazon ECS CLI supports Docker compose file syntax versions 1 and 2.
>
> The following parameters are supported in compose files for the Amazon ECS CLI:
> …
> * `log_driver`
> * `log_opt`

… it's actually version 3 that `ecs-cli` 0.5.0 supports, with `logging.driver` and `logging.options`. Try, for example:

```yaml
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-group: awslogs-containers-dev
```
