### ISSUE TITLE
compose syntax v2 can't interpret volume compose : Invalid timestamp: 

### ISSUE THREAD

**Issue by VinceMD** [aws/amazon-ecs-cli#165]
here is the error:

`$ ecs-cli compose --file docker-compose.yml up
ERRO[0000] Could not parse config for project tmp : Invalid timestamp: '' at line 37, column 8 
ERRO[0000] Unable to open ECS Compose Project            error=Invalid timestamp: '' at line 37, column 8
FATA[0000] Unable to create and read ECS Compose Project  error=Invalid timestamp: '' at line 37, column 8`

Here is the compose file:

version: '2'
services:
[..]
  redis:
    mem_limit: 524288000
    cpu_shares: 100
    image: redis
    volumes:
      - 'redis:/var/lib/redis/data'
volumes:
  redis:
  mysql:

It does not like the last 2 lines although it's fine with docker compose

**Comment by tcco** [comment]
I wish I could use the same compose file for docker-compose and ecs-cli but it seems ecs-cli is just not there yet. Just remove the volumes block and if you utilize the volume, say using volumes_from just call the redis volume like so. 

    volumes_from:
        - redis

**Comment by uttarasridhar** [comment]
Thanks @VinceMD for the feedback. Thanks @tcco for the workaround.

ecs-cli's supported compose options are listed [here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html#cmd-ecs-cli-compose-description).
As of today, we only support services configuration in compose v2.0 file format (not volumes nor network configuration).

**Comment by dsifford** [comment]
@uttarasridhar I'm getting this logged into the terminal when running `up`

```
WARN[0000] Skipping unsupported YAML option...           option name=volumes
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=db
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=phpmyadmin
WARN[0000] Skipping unsupported YAML option for service...  option name=networks service name=wordpress
```

I believe those are all valid v2 config properties.

**Comment by dsifford** [comment]
Context:

Here's the compose file I'm trying to run..

```yml
version: '2'
services:
    wordpress:
        image: visiblevc/wordpress
        ports:
            - 443:443
            - 8080:80
        volumes:
            - ./data:/data
        environment:
            DB_NAME: wordpress
            DB_PASS: <redacted>
            PLUGINS: >-
                list,
                of,
                plugins,
                here
            WP_DEBUG_LOG: 'true'
            WP_DEBUG_DISPLAY: 'true'
            WP_DEBUG: 'true'
    db:
        image: mariadb:10
        environment:
            MYSQL_ROOT_PASSWORD: <redacted>
        volumes:
            - data:/var/lib/mysql
volumes:
    data:
```
