### ISSUE TITLE
ecs-cli scale differs from docker-compose scale

### ISSUE THREAD

**Issue by fingermark** [aws/amazon-ecs-cli#166]
Let's say I have the following file:

```
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
chrome:
  image: selenium/node-chrome
  links:
    - hub
  cpu_shares: 100
```

Now I always want one hub, but the ability to scale the "chrome" nodes.  With docker-compose, I can do `docker-compose scale chrome=20`.  `ecs-cli scale --capability-iam --size 20` doesn't allow me to specify the service I want to scale.  Instead it scales the whole thing.

Or how can I achieve this?
