### ISSUE TITLE
compose does not support SHA256 digests for images

### ISSUE THREAD

**Issue by JohnMaguire** [aws/amazon-ecs-cli#196]
An image in the format of `repository/image@sha256:<hash>` results in the following error:

```
ERRO[0000] Error registering task definition             error="ClientException: Container.image contains invalid characters.\n\tstatus code: 400, request id: 18edc7ea-e7fc-11e6-bffa-33b84e6664b2" family=ecscompose-releases
ERRO[0000] Create task definition failed                 error="ClientException: Container.image contains invalid characters.\n\tstatus code: 400, request id: 18edc7ea-e7fc-11e6-bffa-33b84e6664b2"
FATA[0000] ClientException: Container.image contains invalid characters.
        status code: 400, request id: 18edc7ea-e7fc-11e6-bffa-33b84e6664b2
```

**Comment by sachaos** [comment]
https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/vendor/github.com/aws/aws-sdk-go/service/ecs/api.go#L3164

**Comment by yinshiua** [comment]
This is fixed. You should now be able to specify image using the format.

Tested with sample compose file:
```
version: '2'
services:
  wordpress:
    image: wordpress@sha256:200455a3ff4bd410505d8b36dd2b4364378d49567ae1ce7566106f3015b4a7f7
    cpu_shares: 100
    mem_limit: 5MB
    ports:
      - "80:80"
    links:
      - mysql
  mysql:
    image: mysql
    cpu_shares: 100
    mem_limit: 5MB
    environment:
      MYSQL_ROOT_PASSWORD: password
```
