### ISSUE TITLE
Commands-as-strings don't work (aren't split correctly)

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-cli#2]
In most compose files you have a command as the following
```yaml
hello_world:
    image: busybox
    ports: 
        - "80:80"
    command: echo hi
```

This works fine with `docker-compose`.

The only way I've been able to represent that with `ecs-cli compose` is via the following awkward construct:
```yaml
hello_world:
    image: busybox
    ports: 
        - "80:80"
    command:
        - echo
        - hi
```

**Comment by Kenny-House** [comment]
Ran into this issue yesterday. As mentioned, the behavior is different than with `docker-compose`. Not a huge issue to deal with, but definitely confusing to debug.

Since it's a common practice to use a shell script as the entrypoint that matches against the first argument passed in the command, this difference in behavior will likely pop up frequently for people using popular public repos.

As an example, the public mongo docker image has the following in the entrypoint script:
```
if [ "$1" = 'mongod' ]; then
	chown -R mongodb /data/db

	numa='numactl --interleave=all'
	if $numa true &> /dev/null; then
		set -- $numa "$@"
	fi

	exec gosu mongodb "$@"
fi

exec "$@"
```

With entrypoints following this pattern, with ```ecs-cli compose``` a command with flags like ```mongod --smallfiles``` results in the command being exec'd on the last line of the script as opposed to using ```docker-compose``` which will split the command into separate arguments and would be exec'd in the if statement. 

In the case of this mongo example, the container will simply fail to start with ```ecs-cli compose``` yet run normally with ```docker-compose```

**Comment by pjoe** [comment]
I had a similar issue trying to run something like ```sh -c "command1 --opt=something && command2"```, from what I could see afterwards with docker inspect on the container it just doesn't get translated correct. I also tried:
```yaml
something:
    command:
        - sh
        - -c
        - "command1 --opt=something && command2"
```

Could be there also is some problem with the way quotes in commands are handled

**Comment by sebcreme** [comment]
**+1** on this one just pass time to debug it. I really don't think than behaviour would be different from docker-compose.

**Comment by the-nicolas** [comment]
It´s 2016 now and no one took care about that yet?

Same here, works fine with compose (pass it to entrypoint as arg)
`command: [--mode=gate, --config=/config/config.gate.yml]`

**Comment by rucas** [comment]
Does anyone know how to get this working with celery or uwsgi that require option paramters?

I tried spliting it up into a list but ecs-cli compose seems to hate the `--ini`, `-A`, `--concurrency=2`, etc. Also tried wrapping those options as a string using single/double quotes and that didnt work either and tried using entrypoint.

Excerpt of `aws-compose.yml`:

```yaml
neweyes:
    env_file: .env
    image: rucas/neweyes
    ports:
      - "8000:8000"
    command: 
        - uwsgi 
        - --ini 
        - neweyes.ini
    cpu_shares: 100
    mem_limit: 262144000
    links:
      - redis
      - rabbitmq

worker_default:
    env_file: .env
    image: rucas/neweyes
    cpu_shares: 100
    mem_limit: 262144000
    command: 
        celery -A neweyes:celery worker --loglevel=INFO  
                --concurrency=2 -Q default -n worker1.%h
    links:
      - redis
      - rabbitmq
```

**Comment by rucas** [comment]
For those stuck at this I outlined what i did to make it work.

I guess your Dockerfile **must have an ENTRYPOINT** i just made mine this
```Dockerfile
ENTRYPOINT ["./ops/uwsgi.sh"]
```
...which was a bash script to start uwsgi 

later on in the docker-compose.yml you can override the entrypoint and specify a command

```yaml
worker_default:
    env_file: .env
    image: rucas/neweyes
    cpu_shares: 100
    mem_limit: 262144000
    entrypoint: "./ops/celery.sh"
    command: 
        - default
        - "1"
```
