### ISSUE TITLE
executable file not found in $PATH when running compose command

### ISSUE THREAD

**Issue by gillisd** [aws/amazon-ecs-cli#25]
Below is my docker-compose.yml file that I'm running when using `ecs-cli compose up`
```
hello_world:
  image: busybox
  cpu_shares: 100
  mem_limit: 256288000
  command: 
    - echo hi
```

Regardless of what command I use, I always get the same error:

`System error: exec: \"echo hi\": executable file not found in $PATH" `
