### ISSUE TITLE
Variable substitution from shell environment

### ISSUE THREAD

**Issue by tonysickpony** [aws/amazon-ecs-cli#28]
Docker-compose enabled variable substitution from shell environment now. 
```
web:
    image: "myimage: ${GIT_COMMIT_HASH}"
    ports: 
        - '80:80'
...
```
It will be awesome if ecs-cli support this too. Or maybe this involves the issue with docker version running on ecs instance?
