### ISSUE TITLE
JSON arrays don't work

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-cli#3]
As we know, YAML is a superset of JSON. Anywhere you can use a YAML array you should be able to also use a JSON array. This doesn't work. For example:

```yaml
web:
    image: nginx
    ports: ["80:80"]
```

This works fine with `docker-compose` but with `ecs-cli compose` I get the following error:
`ERRO[0000] Unable to convert yaml to service configs     error=Error parsing: node is not of type list ["80:80"]`

This can be worked around with the folowing:
```yaml
web:
    image: nginx
    ports:
        - "80:80"
        - "443:443"
```
