### ISSUE TITLE
Example configurations with persistent storage?

### ISSUE THREAD

**Issue by kaihendry** [aws/amazon-ecs-cli#318]
It's not clear to me how to make a persistent storage bind after reading http://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html

Are there ecs-cli docker-compose.yml examples for study?

My use case is to run [mongo db](https://hub.docker.com/_/mongo/) and not risk losing /data/db.

**Comment by PettitWesley** [comment]
@kaihendry, thanks for your question. 

I created this compose file (based upon an example I found [here](https://github.com/yeasy/docker-compose-files/blob/master/mongo_webui/docker-compose.yml)).

```
mongo:
    image: mongo:3.0
    hostname: mongo
    expose:
        - "27017"
    volumes:
        - /opt/data/mongo_home:/data/db
    restart: always
    mem_limit: 1024m
```

I then used the ECS CLI to run this compose file. This resulted in the following container definition in the ECS Task Definition:
(I've intentionally omitted fields that are not relevant for this example)

```json
 "containerDefinitions": [
    {
      "volumesFrom": [],
      "mountPoints": [
        {
          "containerPath": "/data/db",
          "sourceVolume": "volume-0",
          "readOnly": false
        }
      ],
      "name": "mongo",
    }
  ],
  "placementConstraints": [],
  "volumes": [
    {
      "host": {
        "sourcePath": "/opt/data/mongo_home"
      },
      "name": "volume-0"
    }
  ],
  "family": "ecscompose-volumes"
}
```

Based upon the docs link that you sent- I think this should work. Let me know if this solves your problem!
