### ISSUE TITLE
Volumnes not working with Fargate: Related 'No space left on device'

### ISSUE THREAD

**Issue by djstein** [aws/amazon-ecs-cli#417]
I am experiencing a ```No space left on device``` error while using Jenkins on Fargate. While the rror thrown is from the JVM, It is my understanding that the data of $JENKINS_HOME directory (/var/jenkins_home/) on the Docker Image gets filled up and then no more builds can be processed. The only way to mitigate this issue seems to be removing the service and recreating it. All configurations made are then lost due to persistent storage being unavailable.

However, I believe the actual way to solve this issue is to mount the `/var/jenkins_home/` directory to the containers filesystem. It is my understanding doing so is done via the standard docker-compose configuration of volumes. Unfortunately, when using Fargate and attempting to `ecs-cli compose service up` with volumes in the compose file, the following error is thrown:
```
ERRO[0000] Error registering task definition             error="ClientException: host.sourcePath should not be set for volumes in Fargate.\n\tstatus code: 400, request id: 5b75c647-ffc3-11e7-9dd1-2736ab6818c3" family=ci
ERRO[0000] Create task definition failed                 error="ClientException: host.sourcePath should not be set for volumes in Fargate.\n\tstatus code: 400, request id: 5b75c647-ffc3-11e7-9dd1-2736ab6818c3"
FATA[0000] ClientException: host.sourcePath should not be set for volumes in Fargate.
	status code: 400, request id: 5b75c647-ffc3-11e7-9dd1-2736ab6818c3
```
This is unexpected when in the documentation for [ecs-cli compose](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html) does not specify that Fargate does not support volumes. So should I change my syntax? OR is there something I am missing about volumes. If yes, it would most be important to show an example of how to use volumes in the documentation (currently the only examples exist in closed issues).

docker-compose.yml
```
  jenkins:
    image: <url>/jenkins:latest
    ports:
      - "8080:8080"

    environment:
      JENKINS: 1
      JAVA_OPTS: -Xmx512m
    mem_reservation: 1024m
    volumes:
      - /opt/data/jenkins_home:/var/jenkins_home
    logging:
      driver: awslogs
      options: 
        awslogs-group: ci
        awslogs-region: us-east-1
        awslogs-stream-prefix: jenkins
```

EDIT: I see that [this is probably the answer](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html), unfortunately I am unsure if this a. works on Fargate and b. can be done using the compose syntax.

**Comment by nathanpeck** [comment]
When you are using volumes on Fargate you can not specify a host `sourcePath`, you just specify the  and Fargate supplies you with disk space from a location on the host of its choice. It's important to note that this is essentially just temp scratch space, anything you store there is gone when the task ends as documented [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_data_volumes.html) under "To provide nonpersistent empty data volumes for containers"

Example:

```
"volumes": [
    {
      "name": "jenkins_scratch_space",
      "host": {}
    }
  ]
```

You should be able to do this using the docker-compose syntax by specifying just the container path without the host path.

**Comment by djstein** [comment]
@nathanpeck thanks for the quick response!
The above example would be for a CloudFormation file written in JSON correct?
I believe the syntax to replicate this in a docker-compose file would be:
```
services:
    jenkins:    
        ...
        volumes:
        - /var/jenkins_home

volumes:
    jenkins_scratch_space:
```
However, I am not sure where the `jenkins_scratch_space` would then be used. Since no source can be specified, `jenkins_scratch_space:/var/jenkins_home` cannot be used. Regardless if a volume is defined or not below services, the JSON output of the Task is below, with the task then stuck in a rebooting loop.
```
 "volumes": [
    {
      "name": "volume-0",
      "host": {
        "sourcePath": null
      }
    }
```

**Comment by djstein** [comment]
any thoughts on this? @nathanpeck @PettitWesley i moved my fargate instances to ec2, and am still not really seeing any persisted data.

**Comment by PettitWesley** [comment]
@djstein, I tried a Docker Compose file simply with this:

```
version: '2'
services:
  jenkins:
    ...
    volumes:
      - :/var/jenkins_home
```

The task launched successfully on Fargate and the registered task definition had this:

```
"mountPoints": [
        {
          "readOnly": false,
          "containerPath": "/var/jenkins_home",
          "sourceVolume": "volume-0"
        }
```

Let me know if this works with your application!

**Comment by djstein** [comment]
@PettitWesley while I believe this is the expected result (creation of volume-0) which I have recreated several times using `volumes: - /var/jenkins_home` (notice the `:` is not included) that data volume does not seem to scale / continues to fill up (which leads me to believe it is still using the 8gb docker image's space in the `/dev/xvda` volume). I am consistently getting `No space left on device` with this approach.
I will attempt again with `:` included.
Currently, I have switched to EC2 instances over Fargate, hoping volumes would work and am currently testing today.

**Comment by djstein** [comment]
@PettitWesley Unfortunately I have been working with this again, with no luck. Using EC2 instances my volumes look as such:
```
version: '2'

services:
  postgres:
    image: repo-for-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    cpu_shares: 100
    mem_reservation: 512m
    logging:
      driver: awslogs
      options: 
        awslogs-group: ci
        awslogs-region: us-east-1
        awslogs-stream-prefix: postgres

  jenkins:
    image: repo-for-jenkins
    ports:
      - "8080:8080"
      - "8000:8000"
    environment:
      JENKINS: 1
      JAVA_OPTS: -Xmx512m
    mem_reservation: 1024m
    volumes:
      - jenkins-data:/var/jenkins_home
    logging:
      driver: awslogs
      options: 
        awslogs-group: ci
        awslogs-region: us-east-1
        awslogs-stream-prefix: jenkins

volumes:
  jenkins-data:
  postgres-data:
```

These end up a JSON config containing:
```
# example in container config:
      "mountPoints": [
        {
          "readOnly": false,
          "containerPath": "/var/jenkins_home",
          "sourceVolume": "volume-0"
        }
      ],

# volumes defined at bottom of json file
  "volumes": [
    {
      "name": "volume-0",
      "host": {
        "sourcePath": "jenkins-data"
      }
    },
    {
      "name": "volume-1",
      "host": {
        "sourcePath": "postgres-data"
      }
    }
  ]
```

And still ended up with `No space left on device` when a pip install was about to run. I am unsure of how to proceed since these EC2 instances were supposed to have volumes outside of the `/dev/xvda`
