### ISSUE TITLE
Fargate task with multiple containers is not working properly

### ISSUE THREAD

**Issue by alihalabyah** [aws/amazon-ecs-cli#425]
Hello AWS Team,

I was exploring Fargate using ecs-cli, I have both the docker-compose.yml and ecs-params.yml files inside my path with correct network, logging configurations and multiple services/containers are described with existing ECR images, the task runs after few minutes fine, however there are no logs generated and the actual service is not working on the exposed port, on the other hand when I try to keep one container per task it works fine and I can see the logs.

Can you please check this since it's a blocker for us moving forward?

**Comment by SoManyHs** [comment]
Hi @alihalabyah,

Sorry to hear you're having issues.  Could you provide the `docker-compose.yml` and `ecs-params.yml` files you are using to describe the multiple containers?

Thanks!

**Comment by alihalabyah** [comment]
Hi @SoManyHs 

Sure, they are below:

docker-compose.yml
```
version: '2'

services:

  elasticsearch:
    image: ecr-image-url
    ports:
      - "9200:9200"
    logging:
      driver: awslogs
      options: 
        awslogs-group: company
        awslogs-region: us-east-1
        awslogs-stream-prefix: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"

  logstash:
    image: ecr-image-url
    ports:
      - "5000:5000"
    logging:
      driver: awslogs
      options: 
        awslogs-group: company
        awslogs-region: us-east-1
        awslogs-stream-prefix: logstash
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"

  kibana:
    image: ecr-image-url
    ports:
      - "5601:5601"
    logging:
      driver: awslogs
      options: 
        awslogs-group: company
        awslogs-region: us-east-1
        awslogs-stream-prefix: kibana
```

ecs-params.yml

```
version: 1
task_definition:
  task_execution_role: ecsExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0000000"
        - "subnet-0000000"
      security_groups:
        - "sg-00000000"
      assign_public_ip: ENABLED
```
