### ISSUE TITLE
[service up] You cannot specify an IAM role for services that require a service linked role

### ISSUE THREAD

**Issue by Tensho** [aws/amazon-ecs-cli#426]
I already have ECS cluster created by wizard, so most of roles (including service-linked) was created by 

- ecsInstanceRole
- ecsServiceRole
- ecsAutoscaleRole
- ecsExecutionRole
- AWSServiceRoleForECS (service-linked role)

I try to create a brand new ECS cluster with ECS CLI entirely. So I created ALB upfront as far as the current ECS CLI version (1.3.0) doesn't support it out of the box with some additional flag.

The next command creates ECS cluster successfully in already defined VPC and subnets:
```
$ ecs-cli up --cluster my-ecs-staging \
        --instance-role ecsInstanceRole \
        --no-associate-public-ip-address \
        --vpc vpc-11111111 \
        --subnets subnet-22222222,subnet-33333333 \
        --keypair ecs-user \
        --size 2 \
        --verbose
```
But when I try to launch web service with the next configuration and command:
```
# docker-compose.ecs.yml

version: '2'

services:
  resolver-company-admin-web:
    image: arn:aws:ecr:eu-west-1:444444444444444:repository/rails-app
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: my-ecs-staging
        awslogs-region: eu-west-1
        awslogs-stream-prefix: web
    environment:
      RAILS_ENV: staging
```
```
# ecs-params.yml

version: 1

task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ecsExecutionRole
  task_size:
    cpu_limit: 256
    mem_limit: 0.5GB

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-22222222
        - subnet-33333333
```
```
$ ecs-cli compose --file docker-compose.ecs.yml \
                --project-name web \
                --task-role-arn rails-app-web \
                --verbose \
                service up \
                --target-group-arn arn:aws:elasticloadbalancing:eu-west-1:444444444444444:loadbalancer/app/my-ecs-alb/cfaabea0f052fa3d \
		--container-name web \
		--container-port 3000 \
		--role ecsServiceRole
```
I receive roles related error:
```
ERRO[0002] Error creating service                        error="InvalidParameterException: You cannot specify an IAM role for services that require a service linked role.\n\tstatus code: 400, request id: 55555555-5555-5555-5555-555555555555" service=web
```
Cloud you give me insight where I should look at to resolve that issue?

```
$ ecs-cli --version
ecs-cli version 1.3.0 (*UNKNOWN)
```
