### ISSUE TITLE
FARGATE:  Error when trying to create task definition from docker-compose file

### ISSUE THREAD

**Issue by jasonrhaas** [aws/amazon-ecs-cli#463]
### Summary
```
RRO[0000] Error registering task definition             error="ClientException: No Fargate configuration exists for given values.\n\tstatus code: 400, request id: 7a554bad-3384-11e8-8269-afdeb5f3beb5" family=docker-sonarqube
```

I'm following the tutorial here  -- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial_fargate.html

When I get "Step 5:  Deploy the Compose File to a Cluster" I am getting an error.

### Description
Command that was run in Step 5 (with some modifications):
`ecs-cli compose --file aws-docker-compose.yml service up --create-log-groups`

`ecs-cli --version` = ecs-cli version 1.4.2 (*UNKNOWN)

### Expected Behavior
Task definition is deployed.

### Observed Behavior
```
ERRO[0000] Error registering task definition             error="ClientException: No Fargate configuration exists for given values.\n\tstatus code: 400, request id: 4a3464f2-3383-11e8-89e8-49356186c7a1" family=docker-sonarqube
ERRO[0000] Create task definition failed                 error="ClientException: No Fargate configuration exists for given values.\n\tstatus code: 400, request id: 4a3464f2-3383-11e8-89e8-49356186c7a1"
FATA[0000] ClientException: No Fargate configuration exists for given values.
```

### Config files
* docker-compose.yml

```
version: '2'

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=xxxx
      - SONARQUBE_JDBC_PASSWORD=xxxx
      - SONARQUBE_JDBC_URL=xxxx
    logging:
      driver: awslogs
      options: 
        awslogs-group: c137
        awslogs-region: us-east-1
        awslogs-stream-prefix: sonarqube
```

* ecs-params.yml

```
version: 1
task_definition:
  task_execution_role: ecsExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 3.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-be7773e3"
        - "subnet-d266af98"
      security_groups:
        - "sg-5c999d2a"
      assign_public_ip: ENABLED
```
