### ISSUE TITLE
Shared named volumes on Fargate via compose

### ISSUE THREAD

**Issue by mlapierre** [aws/amazon-ecs-cli#481]
### Summary
I would like to be able to create tasks on Fargate using docker compose files with named volumes shared between containers.

### Description
I understand that I can't mount a host directory as a volume when using Fargate, which is why `host.sourcePath` should not be set. However, it is possible to use shared named volumes if I configure them using `aws ecs register-task-definition`, but I'd like to be able to do it via compose.

`ecs-cli version 1.5.0 (0bfcecd)`
`go version go1.10.1 windows/amd64`

### Expected Behavior

For example, this compose file:

    version: "2"
    services:
      web:
        image: nginx
        volumes:
          - logs:/var/logs
          
specifies a named volume `logs` mounted on the container path `/var/logs`
            
The compose file should be equivalent to this task definition, which is valid when created manually and assigned via `aws ecs register-task-definition` (some fields excluded for brevity):

    {
        "volumes": [
            {
                "name": "logs"
            }
        ],
        "containerDefinitions": [
            {
                "image": "nginx",
                "mountPoints": [
                    {
                        "sourceVolume": "logs",
                        "readOnly": false,
                        "containerPath": "/var/logs"
                    }
                ]
            }
        ]
    }
        
The above is what I'd expect the cli to produce, i.e., a name instead of a source path, matched with the sourceVolume for the mountPoint. Then I could configure another container to use the same sourceVolume.

### Observed Behavior

But when I try to create a service using the compose file:

    ecs-cli compose --project-name volume-test --file nginx.yml service create
    
I get this error:    
    
    FATA[0000] ClientException: host.sourcePath should not be set for volumes in Fargate.
            status code: 400, request id: d5dba72d-43f9-11e8-89d2-8f5625f69ed7

It seems the cli doesn't understand when a compose file specifies a named volume, not a host source path

**Comment by PettitWesley** [comment]
@mlapierre I'm marking this as a feature request; this is something we should definitely support. I can't provide any specific timeline, but hopefully this is something we will get to fairly soon.

For your example, the [compose 2](https://docs.docker.com/compose/compose-file/compose-file-v2/#volume-configuration-reference) experience that we will likely support would look like this:

```
version: "2"
services:
  web:
    image: nginx
    volumes:
      - logs:/var/logs
volumes:
  logs:
```

Which as you noted should result in a task def like this:

```
{
    "volumes": [
        {
            "name": "logs"
        }
    ],
    "containerDefinitions": [
        {
            "image": "nginx",
            "mountPoints": [
                {
                    "sourceVolume": "logs",
                    "readOnly": false,
                    "containerPath": "/var/logs"
                }
            ]
        }
    ]
}
```

**Comment by blueimp** [comment]
Hi, I've encountered the same issue today.

I've added a [pull request](https://github.com/aws/amazon-ecs-cli/pull/489) for it.

The code follows @PettitWesley's suggestion regarding the [compose 2 volume configuration](https://docs.docker.com/compose/compose-file/compose-file-v2/#volume-configuration-reference), so defining the named volumes at the top level is a requirement:

```yml
version: "2"
services:
  web:
    image: nginx
    volumes:
      - logs:/var/logs
volumes:
  logs:
```

**Comment by PettitWesley** [comment]
@blueimp Ha ha I was literally starting to write the code for this myself, but you beat me to it! I'll review and test your PR today.

**Comment by blueimp** [comment]
Oh, sorry about that!
I was actually going to write a comment first, letting you know I'd like to work on it (following the [contributing guide](https://github.com/aws/amazon-ecs-cli/blob/master/CONTRIBUTING.md#contributing-code), but first wanted to check it out and see how complex it is.
Well and then I was already half-way writing the code. 😁 

Thanks for reviewing!

**Comment by arliber** [comment]
Please forgive me for reviving an old issue but I'm not sure how to utilize this in my case - any help would be appreciated.

One service (cloud sql proxy) in my compose file intended for Fargate requires a credentials file that I can provide only through a volume like so:

```
sqlproxy-service-database:
      container_name: sqlproxy-service-database
      image: b.gcr.io/cloudsql-docker/gce-proxy:latest
      command: /cloud_sql_proxy <REDUCTED> -credential_file=/secrets/cloudsql/credentials.json
      ports:
        - 3307:3307
      volumes:
        - ./credentials.json:/secrets/cloudsql/credentials.json
```

This currently throws the `host.sourcePath should not be set for volumes in Fargate` error. How does the PR above help with that? 

Thanks you
