### ISSUE TITLE
Support Service Discovery when configuring network

### ISSUE THREAD

**Issue by HUSSTECH** [aws/amazon-ecs-cli#485]
### Summary
It appears as if the current version of the CLI does not support service discovery yet. When bringing a service down then up again, it is not recreated with its service discovery network configuration in place.

### Description

- ecs-cli version: 1.4.2
- go version: 1.9.5
- platform: Ubuntu 16.04 and Debian Jessie

I had manually created an ecs service from the console, so that I could set up service discovery manually first to try it out. This was created correctly, and was working as expected. Then when I needed to update the service with a new task definition, I used `service down` then `service up` via the cli. When the service was back up again, the service discovery settings were not present on the service anymore.

### Config files
* ecs-params.yml
```
version: 1
task_definition:
  ecs_network_mode: awsvpc

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-xxxxxx
      security_groups:
        - sg-xxxxxxx
```

### Observed Behavior
service is correctly brought down, then up again. But upon re-creation, if there was already ECS service discovery configured, it is no longer present. i.e. There is no route53 entry. As if it was removed. You have to use the console to recreate the service with service discovery.
