### ISSUE TITLE
Some ECS features are not supported

### ISSUE THREAD

**Issue by euank** [aws/amazon-ecs-cli#5]
Running `ecs-cli compose up` with the following file:

```yaml
privileged_example:
    image: busybox
    privileged: true
    command:
        - sh
        - "-c"
        - "hostname changed; hostname"
```

Results in the output of:
`WARN[0000] Skipping unsupported YAML option...           option name=privileged`
and the container running incorrectly.
