### ISSUE TITLE
i cant see nothing in instance tabs

### ISSUE THREAD

**Issue by harryhan24** [aws/amazon-ecs-cli#511]
### Summary

i cant see ec2 in ecs-instance tab
### Description

when i excute this command, i can see my ec2 instance in EC2 page 
but whenever i check ecs-instance in cluster page, i cant see nothing.
even if i type ecs-cli compose up, there is error "no instance"
but ec2 have generated wihtout any errors in cloudwatch.

but when i try with no-vpc-setting, it works. am i missing something?

```bash
ecs-cli up --size 1 \
           --instance-type t2.micro \
           --cluster-config node-mongo \
           --instance-role ecsInstanceRole \
           --keypair harry-first-pem \
           --verbose
```

### Config files
* docker-compose.yml
```bash
ecs-cli up --size 1 \
           --instance-type t2.micro \
           --cluster-config node-mongo \
           --instance-role ecsInstanceRole \
           --keypair harry-first-pem \
           --vpc vpc-f1d3fd99 \
           --subnets subnet-7ea03232,subnet-0baa1056780666c67 \
           --security-group sg-05f033683a82b5413 \
           --verbose
```
* ecs-params.yml

* ~/.ecs/config
 ```yml
version: v1
default: node-mongo
 clusters:
  node-mongo:
   cluster: node-mongo
   region: ap-northeast-2
   default_launch_type: EC2
```

### Observed Behavior
i cant see ec2 in ecs-instance tab
