### ISSUE TITLE
Difference between `compose service up` and `compose up`

### ISSUE THREAD

**Issue by CoreyCole** [aws/amazon-ecs-cli#543]
### Summary

The documentation for [compose up](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-up.html) is a little vague in how it is different from [compose service up](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-service.html)

It seems like they're not meant to be used interchangably. It seems like `compse service up` is for updating a single service, while `compose up` is for deploying an entire new cluster? 🤔 

## Question
How do I deploy to a fargate cluster using a load balancer without having to individually launch service-by-service?

### Description

I'm having trouble linking an ALB that I've already created to my cluster using `compose up`. It doesn't seem like it's an option to pass `--load-balancer-name value` or `--target-group-arn value` to `compose up`, why is this?

Trying to use `compose service up`, I get an error stating I need to provide a container name:
```
$ ecs-cli compose --cluster staging --project-name staging \
    --ecs-params infra/docker/ecs-params.staging.yml \
    --file infra/docker/ecs-compose.staging.yml \
    --region us-west-2 service up \
    --target-group-arn arn:aws:elasticloadbalancing:us-west-2:my-aws-id:targetgroup/staging/my-target-group-id \
    --launch-type FARGATE
```
```
INFO[0000] Using ECS task definition                     TaskDefinition="staging:40"
ERRO[0000] Error creating service                        error="InvalidParameterException: Container Name can not be blank.\n\tstatus code: 400, request id: xxxxxxxx-734a-11e8-bba9-738152ed4ad2" service=staging
FATA[0000] InvalidParameterException: Container Name can not be blank.
	status code: 400, request id: xxxxxxxx-734a-11e8-bba9-738152ed4ad2
```

### Config files

* ecs-compose.staging.yml
```
version: '3'

services:
  app:
    logging:
      driver: awslogs
      options:
        awslogs-group: staging
        awslogs-region: us-west-2
        awslogs-stream-prefix: staging
    ports:
      - 5000:5000
    image: my-aws-id.dkr.ecr.us-west-2.amazonaws.com/ecs-img-1
    env_file:
      - docker-ecs.staging.env

  state:
    logging:
      driver: awslogs
      options:
        awslogs-group: staging
        awslogs-region: us-west-2
        awslogs-stream-prefix: staging
    ports:
      - 3000:3000
      - 8080:8080
    image: my-aws-id.dkr.ecr.us-west-2.amazonaws.com/ecs-img-2
    env_file:
      - docker-ecs.staging.env
```

* ecs-params.staging.yml
```
version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_role_arn: arn:aws:iam::my-aws-id:role/myFargateRole
  task_execution_role: arn:aws:iam::my-aws-id:role/myFargateRole
  task_size:
    cpu_limit: 256
    mem_limit: 0.5GB
  services:
    app:
      essential: true
    state:
      essential: true

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-my-subnet-id-1
        - subnet-my-subnet-id-2
      assign_public_ip: ENABLED
```

* ~/.ecs/config
```
version: v1
default: default
clusters:
  default:
    cluster: staging
    region: us-west-2
    default_launch_type: ""
```
