### ISSUE TITLE
Version 1.6.6 fails to bring service up

### ISSUE THREAD

**Issue by fogfish** [aws/amazon-ecs-cli#546]
### Summary
`ecs-cli` version 1.6.6 fails with

```
time="2018-06-26T12:33:48Z" level=error msg="Unable to open ECS Compose Project" error="mem_limit must be greater than mem_reservation"
time="2018-06-26T12:33:48Z" level=fatal msg="Unable to create and read ECS Compose Project" error="mem_limit must be greater than mem_reservation"
```

### Description

```
ecs-cli compose -c mycluster -p myapp --task-role-arn myrole -f compose.yml service up
```

```
# compose.yml
#
version: '2'

services:
  myapp:
    image: "xxx:1.2.0"
    mem_reservation: 128m

    logging:
      driver: awslogs
      options:
        awslogs-group: mygroup
        awslogs-region: eu-west-1
        awslogs-stream-prefix: myapp

    environment:
       - "X=1"
```

`eps-cli` is used within latest `centos` docker image on CodeBuild

### Config files

No config files

### Expected Behavior

`ecs-cli ... service up` brings service successfully

### Observed Behavior

`ecs-cli ... service up` fails with

```
time="2018-06-26T12:33:48Z" level=error msg="Unable to open ECS Compose Project" error="mem_limit must be greater than mem_reservation"
time="2018-06-26T12:33:48Z" level=fatal msg="Unable to create and read ECS Compose Project" error="mem_limit must be greater than mem_reservation"
```
