### ISSUE TITLE
provide cluster details in ~/.ecs/config [kind question]

### ISSUE THREAD

**Issue by jmarcos-cano** [aws/amazon-ecs-cli#556]
### Summary
Is there any way to define cluster specifics within the config (yaml file) ?

### Description
Currently (AFAIK) in the documentation it states that you should use flags in order to configure your cluster details 

`ecs-cli up --keypair id_rsa --capability-iam --size 2 --instance-type t2.medium --cluster-config ec2-tutorial`

So I was wondering if there's any chance one can specify details in the config yaml like this?

```yaml
version: v1
default: ec2-tutorial
clusters:
  ec2-tutorial:
    cluster: ec2-tutorial
    region: us-west-2
    default_launch_type: EC2
   
   size: 2
   instance_type: t2.medium
   keypair: id_rsa
```
