### ISSUE TITLE
Regression: v1.6.0 does not create docker data volumes

### ISSUE THREAD

**Issue by mkjsix** [aws/amazon-ecs-cli#559]
### Summary
With ecs-cli v1.6.0 docker volumes are not created anymore, we had to revert back to v1.5.0.

### Description

These are our commands:
```
ecs-cli configure --region eu-central-1 --cluster "gapp-ovs-prod"
ecs-cli compose service up --deployment-min-healthy-percent 0
```

### Config files

* docker-compose.yml

```yml
version: '2'
volumes:
  gapp-ovs-mongodb-data: null
services:
  gapp-ovs-mongodb:
    container_name: gapp-ovs-mongodb
    image: 'mongo:3.6'
    logging:
      driver: json-file
      options:
        max-size: 500k
        max-file: '10'
    volumes:
      - 'gapp-ovs-mongodb-data:/data/db'
    ports:
      - '27017'
```

We expected the `gapp-ovs-mongodb-data` volume to be created with v1.6.0 like it was with v1.5.0

Volumes with ecs-cli v1.5.0:
```
$ docker volume ls
DRIVER              VOLUME NAME
local               63d602131325d806fcfd04d52d52dd09835275ba69bbe81347c36afbc4049ab2
local               gapp-ovs-mongodb-data
```

### Observed Behavior

No named docker volume created with ecs-cli v1.6.0

```
$ docker volume ls
DRIVER              VOLUME NAME
local               134d644a7303e2da11d1f05cbcc3b3b36f400f6b8e570962d8e43bd6f80397a3
local               207dbdba83f1ce4f91dc6abe5e2af1a547e666fe40a7fd752cc5c281c3195a66
```

**Comment by PettitWesley** [comment]
@mkjsix first of all, apologies for how it has taken us to get to this issue. 

> With ecs-cli v1.6.0 docker volumes are not created anymore, we had to revert back to v1.5.0.

 Docker volumes are being created with `v1.6.0`, they just don't have deterministic names anymore. But you're right, there has been a change in behavior.

With v1.6.0 we [added support named volumes](https://github.com/aws/amazon-ecs-cli/pull/489) that can be shared between containers in the same task.

I used this docker compose file:

```
version: '2'
services:
  container1:
    image: nginx
    volumes:
      - shared:/shared
      - notshared:/notshared
  container2:
    image: nginx
    volumes:
      - shared:/sharedwithmetoo

volumes:
  shared:
  notshared:
```

With `v1.5.0`, I get this in the task definition:

```
  "volumes": [
    {
      "name": "volume-0",
      "host": {
        "sourcePath": "shared"
      }
    },
    {
      "name": "volume-1",
      "host": {
        "sourcePath": "notshared"
      }
    }
  ]
```

In `v1.5.0` the top level volumes key was ignored in compose, so the volumes get random names in the ECS Task Definition which means that they can not be shared between containers.

On the EC2 instance, the volumes are named, however, because we set the `sourcePath` field:

```
$ docker volume ls
DRIVER              VOLUME NAME
local               notshared
local               shared
```

With `v1.6.0`, the task definition volumes section is different:

```
"volumes": [
    {
      "name": "notshared",
      "host": {
        "sourcePath": null
      }
    },
    {
      "name": "shared",
      "host": {
        "sourcePath": null
      }
    }
  ]
```

And on the EC2 instance we get:

```
$ docker volume ls
DRIVER              VOLUME NAME
local               ecs-issue559-2-notshared-88f0c1d8b4c5f9fd1500
local               ecs-issue559-2-shared-94a6b8ebfb84c28adb01
```

The volumes are 'named' in the sense that they contain the names we gave them in Compose. I launched the same compose file using Docker Compose locally, and the result is fairly similar (my project name is "issue559"):

```
$ docker-compose up
Creating network "issue559_default" with the default driver
Creating volume "issue559_shared" with default driver
Creating volume "issue559_notshared" with default driver
...
```

What is your exact use case for the name of the volumes on ECS? If you note, the output I got with `v1.6.0` is a bit different than yours. This is because I am using the newest AMI, `amzn-ami-2018.03.d-amazon-ecs-optimized` which contains Agent `1.20.0` which was just released and seems to have some [Docker Volume changes](https://github.com/aws/amazon-ecs-agent/releases/tag/v1.20.0). Please note that there is a [known bug when upgrading to this new version of the Agent from an older version](https://github.com/aws/amazon-ecs-agent/issues/1507).
