### ISSUE TITLE
ecs-cli compose test

### ISSUE THREAD

**Issue by Spechal** [aws/amazon-ecs-cli#569]
### Summary
As a time saver when building images, it would be nice if I could run an ecs-cli compose ... --check to validate the syntax of the docker-compose.yml instead of building all of my images only to find out a config option isn't configured up to snuff.

I suspect it's the healthcheck ... all I did was add it and switch to v3 docker-compose.yml

### Description
```
ecs-cli compose -f docker-compose.ENV.yml -r us-east-1 -c XXX -p XXX service up --timeout 120 --container-name XXX --container-port XXX --target-group-arn arn:aws:elasticloadbalancing:us-east-1:XXX:targetgroup/XXX/XXX
```

### Config files
```
version: '3'
services:
  XXX:
    image: XXX.dkr.ecr.us-east-1.amazonaws.com/XXX/XXX/XXX
    mem_limit: XXXm
    mem_reservation: XXXm
    cpu_shares: XXX
    ports:
      - "0:80"
    links:
      - uwsgi
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/monitor"]
      interval: 10
      timeout: 2
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /apps/XXX/XXX
        awslogs-stream-prefix: nginx
  uwsgi:
    image: XXX.dkr.ecr.us-east-1.amazonaws.com/XXX/XXX/XXX
    mem_limit: XXXm
    mem_reservation: XXXm
    cpu_shares: XXX
    environment:
     LOG_LEVEL: 'DEBUG'
     DB_NAME: 'XXX'
     DB_USER: 'XXX'
     DB_PASSWORD: 'XXX'
     DB_HOST: 'XXX'
     DB_PORT: 5432
     DJANGO_DEBUG_SETTING: 1
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /apps/XXX/XXX
        awslogs-stream-prefix: uwsgi
```

Output:
```
level=error msg="Unable to open ECS Compose Project" error="Configuration contains forbidden properties"
level=fatal msg="Unable to create and read ECS Compose Project" error="Configuration contains forbidden properties"
```

**Comment by allisaurus** [comment]
Hi @Spechal - re: forbidden properties, compose 3 [no longer accepts mem_limit, mem_reservation, or cpu_shares as fields on a service](https://docs.docker.com/compose/compose-file/#resources) (they've been subsumed within `deploy`, which is a swarm-specific key). To continue using these fields with the ECS CLI, you can specify them in an [ecs-params.yml](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose.html#cmd-ecs-cli-compose-ecsparams) file.

Re: `env_file`, I was able to run `compose up` with a version '3' project that included this key (and added the vars within to my service) - @mhumeSF , would you please add your docker-compose.yml and the env_file you're trying to pass in so we can see how your project is structured? Thanks!

**Comment by mhumeSF** [comment]
Just bumping... lemme dig up the commit

**Comment by mhumeSF** [comment]
Just tested this again. Still getting an error with `verion: '3'` 
```
ecs-cli compose --file docker-compose.yml  --project-name $family up --cluster $CLUSTER --region us-east-1
time="2018-08-14T17:13:12Z" level=error msg="Unable to open ECS Compose Project" error="Configuration contains forbidden properties"
time="2018-08-14T17:13:12Z" level=fatal msg="Unable to create and read ECS Compose Project" error="Configuration contains forbidden properties"
```

```
version: '3'

services:
  sports-api:
    image: example/example:latest
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:example.com;PathPrefixStrip:/example"
    env_file: .env.dev
    environment:
      - EXAMPLE=EXAMPLE
    mem_limit: 2048M
    ports:
      - "8080"
```
