### ISSUE TITLE
mem_limit not followed

### ISSUE THREAD

**Issue by FernandoMiguel** [aws/amazon-ecs-cli#570]
### Summary
trying to create an ecs service with mem_reservation set but no mem_limit
but the service always sets a value equal to mem_reservation

### Description
$ ecs-cli compose --project-name ECSCLI --file docker-compose.yml --ecs-params ecs-params.yml create --launch-type EC2

### Config files

* ecs-params.yml
```yml
version: 1
task_definition:
  services:
    ECSCLI:
      mem_limit: "0"
      mem_reservation: "0.050GB"
```

**Comment by allisaurus** [comment]
Hi @FernandoMiguel - thanks for reporting this! Looks like this is a bug in how the ECS CLI is validating memory; you should be able to specify mem_reservation w/o setting mem_limit. However, please note that if you do specify both values, mem_limit needs to be higher than mem_reservation: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html#ECS-Type-ContainerDefinition-memory

In the meantime, one workaround would be to set mem_limit to a value higher than 0.05GB so that 0.05GB is not enforced as a hard limit on your container.

**Comment by FernandoMiguel** [comment]
not setting `mem_limit` makes it set the same value as `mem_reservation`

so far we have resorted to set `mem_limit` the same as the instance, but sounds like a bad workaround

**Comment by codepushr** [comment]
Any updates :/ ?

**Comment by codepushr** [comment]
Another thing that confuses me:

According to -- https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-ecs-supports-memory-and-cpu-limits-at-the-task-level/
is should be sufficient to set a memory size on the task level.

I tried this just now and I'm getting the `RESOURCE:MEMORY` error. Its still forcing me to set the memory limits on the container level.

Is this intended? Because I wished I could let the OS/ecs agent handle it and have dynamic container memory limits.

**Comment by FernandoMiguel** [comment]
AFAIK you have to always set at least a soft limit per container

**Comment by codepushr** [comment]
@FernandoMiguel I see, thanks. Is the intended behaviour, that there is not hard limit (=0) and therefore no container kills on threshold exceeds, or that the mem_limit must be set to mem_reservation+1 so that it's always greater.

**Comment by allisaurus** [comment]
Hi @codepushr - can you tell me what command you're running when you get the `RESOURCE:MEMORY` error? This usually indicates that no EC2 instances in your cluster have sufficient memory available to run the task, vs. an issue with an invalid task configuration. (However if you're using `Fargate` this should not be a constraint). If you can run `ecs-cli compose create` successfully, then you might try scaling your cluster, reducing the amount of task-level memory requested, or launching in `Fargate` mode.

As you point out, it should be sufficient to specify only task-level resources (I was able to run `ecs-cli compose create` with only `task_size` resources set), but please note that the esc-cli will currently default `mem_limit` for a container with no specified memory (res or limit) to 512. 

I don't believe this default behavior is correct when task-level `mem_limit` is set, so we'll work on changing that along with removing the behavior that sets `mem_limit` to the same value as `mem_reservation`. 

Our validation around memory seems to have accumulated some inconsistencies over time and we're currently working to addressing this. Apologies for the delay, and please let me know if scaling your cluster or adjusting task-level memory helps in the meantime.

**Comment by PettitWesley** [comment]
`v1.12.1` contains a fix for this

**Comment by codepushr** [comment]
@allisaurus @PettitWesley Thanks for the reply and sorry for my late response. v.1.12.1 indeed solves the issue of following the optional mem_limit.

However, I'm running into another weird problem:
Currently, I have set a fixed memory on task size and a reservation in my containers. Still, my machine memory gets exceeded and unresponsive.

```
version: 1
task_definition:
  task_size:
    cpu: 896
    memory: 776
  services:
    service1:
      mem_reservation: 256M
    service2:
      mem_reservation: 128M
    servicevolume:
      mem_reservation: 8M
      essential: false
    rabbitmq:
      mem_reservation: 128M
    redis:
      mem_reservation: 128M
    mongodb:
      mem_reservation: 128M
```

As you can see the task should get capped at around 776 MiB, but htop reports a 99% RAM usage when I enter my service container and run 2 intensive processes on purpose. As described above my machine then gets super slow.

Have I misunderstood the conception?

**Comment by allisaurus** [comment]
@codepushr Actually, based on the `ecs-params` content you provided it looks like the field names for task level resources are incorrect. Task memory is actually `mem_limit` and cpu is `cpu_limit` (see [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-ecsparams.html)). So your ecs-params.yml should look like:

```
version: 1
task_definition:
  task_size:
    cpu_limit: 896
    mem_limit: 776
  services:
    service1:
      mem_reservation: 256M
    service2:
      mem_reservation: 128M
    servicevolume:
      mem_reservation: 8M
      essential: false
    rabbitmq:
      mem_reservation: 128M
    redis:
      mem_reservation: 128M
    mongodb:
      mem_reservation: 128M
```

Can you try correcting the field names and re-testing? Thanks, and apologies for not noticing this discrepancy earlier.
