### ISSUE TITLE
Template placeholder substitution in ecs task from docker-compose.yml

### ISSUE THREAD

**Issue by silent-vim** [aws/amazon-ecs-cli#603]
### Summary
Hi, docker has support for using go based template variables in the compose file to substitute when the service/tasks are created. This is the link for the same (https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates). 

When scaling the ecs service tasks is it possible to use this information such as task name and number through a template. For example, when running multiple instances of a task such we would like to know in the service to which scaled instance it corresponds for logging. 

Service are created using latest `ecs-cli compose service create` but the template variables are not substituted.

**Comment by SoManyHs** [comment]
Hi @silent-vim,

ECS does not currently support docker template placeholders, unfortunately. We do support regular variable interpolation for all versions of docker-compose. (See #537) 

You mentioned using these in a compose file -- could you perhaps include an example docker compose file with how you'd like to use the template placeholders? Are you also looking to use template placeholders in flags, and if so could you provide an example of the command you are trying to run that includes a placeholder?

Thanks.

**Comment by SoManyHs** [comment]
Closing due to lack of response.

**Comment by mrwillis** [comment]
The main application of this for me is the `image` tag. It's nice to increment version -> build image -> push image to ECR -> create task definition to point to new image. Always using the latest tag is not very practical. I think this would be the most common application since in general these files don't change once you have the service/task set-up. For example:

```yml
version: '3'
services:
  app:
    image: repo:${PACKAGE_VERSION}
    logging:
      driver: awslogs
      options:
        awslogs-group: group
        awslogs-region: ca-central-1
        awslogs-stream-prefix: app
```
