### ISSUE TITLE
mem_limit defaults to 512MB

### ISSUE THREAD

**Issue by esetnik** [aws/amazon-ecs-cli#606]
### Summary

`mem_limit` defaults to 512MB

### Description
When running `ecs-cli compose service up` if `mem_limit` is not specified in `ecs-params.yml` for each service then the service defaults to 512MB hard limit. This is incorrect according to the Fargate documentation which states that "If you are using Docker compose version 3, this field is optional and must be specified in the ECS params file rather than the compose file."

### Config files

* docker-compose.yml
```
version: "3"
services:
  db:
    image: mariadb
```

* ecs-params.yml
```
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 8GB
    cpu_limit: 1vcpu
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "REDACTED"
        - "REDACTED"
      security_groups:
        - "REDACTED"
      assign_public_ip: ENABLED
```
* ~/.ecs/config
```
version: v1
default: REDACTED
clusters:
  REDACTED:
    cluster: REDACTED
    region: us-east-1
    default_launch_type: FARGATE
```

### Expected Behavior
The default memory limit should be 0 which means all that all containers share the memory allocated to the task

### Observed Behavior
The default memory limit is set to 512MB. Additionally, overriding the memory limit to 0 does not work.
```
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 8GB
    cpu_limit: 1vcpu
  services:
    db:
      mem_limit: 0
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "REDACTED"
        - "REDACTED"
      security_groups:
        - "REDACTED"
      assign_public_ip: ENABLED
```
