### ISSUE TITLE
ecs-cli compose  with multiple input files

### ISSUE THREAD

**Issue by logemann** [aws/amazon-ecs-cli#608]
### Summary
ecs-cli compose --file docker-compose.yml  --file docker-compose-aws.yml service up

Doesnt work. According to the changelog, multiple compose files are supported lately.

### Description
My overrides in the second compose wont get picked up. I have overridden a port mapping to equal values so that AWS doesnt complain but it gets ignored.

### Config files
* docker-compose.yml
 ```
 foo-db:
    build: ./database
    container_name: foo-db
    image: "yyyyyyyy.dkr.ecr.eu-central-1.amazonaws.com/foo-db:latest"
    volumes:
     - mariadbdata:/var/lib/mysql
    ports:
      -  3336:3306
```

* docker-compose-aws.yml
```
  foo-db:
    logging:
      driver: "awslogs"
      options:
         awslogs-region: "eu-central-1"
         awslogs-group: "foo-ecs"
         awslogs-stream-prefix: "foo-db"
    ports:
      -  3306:3306
```

### Expected Behavior
a working stack

### Observed Behavior

```
ERRO[0000] Error registering task definition             error="ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match.\n\tstatus code: 400, request id: afe2d637-b8da-11e8-bda0-1be48cb1b54b" family=netversys
ERRO[0000] Create task definition failed                 error="ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match.\n\tstatus code: 400, request id: afe2d637-b8da-11e8-bda0-1be48cb1b54b"
FATA[0000] ClientException: When networkMode=awsvpc, the host ports and container ports in port mappings must match.
```
