### ISSUE TITLE
is compose run supposed to work on fargate?

### ISSUE THREAD

**Issue by jpaas** [aws/amazon-ecs-cli#625]
### Summary
I can create a fargate cluster and deploy a compose file to create a service, but I can't use compose to run a single task using the same configuration.

### Description
I can deploy a service with 2 tasks, web and worker like so: 
```
ecs-cli compose --ecs-profile karma --cluster-config karma-backend-staging --file ./deploy/docker-compose.staging.yml --ecs-params ./deploy/ecs-params.staging.yml --project-name karma-backend-staging service up --create-log-groups
```

But if I try to run a one-time task using:
```
ecs-cli compose --ecs-profile karma --cluster-config karma-backend-staging --file ./deploy/docker-compose.staging.yml --ecs-params ./deploy/ecs-params.staging.yml run worker "echo test"
```

I get:
```
INFO[0001] Using ECS task definition                     TaskDefinition="deploy:5"
ERRO[0001] Error running tasks                           error="InvalidParameterException: Network Configuration must be provided when networkMode 'awsvpc' is specified.\n\tstatus code: 400, request id: 2828d597-c717-11e8-bd7e-71fd0be676be" task definition="arn:aws:ecs:us-east-1:023742962703:task-definition/deploy:5"
```
### Config files
docker-compose.yml:
```
version: "3"

services:
  web:
    command: bundle exec rails s
    env_file: .env.docker.staging
    environment:
      - SERVICE_NAME=web
    image: 023742962703.dkr.ecr.us-east-1.amazonaws.com/karma_backend_rails:test2
    logging:
      driver: awslogs
      options:
        awslogs-group: staging
        awslogs-region: us-east-1
        awslogs-stream-prefix: staging
    ports:
      - "80:80"

  worker:
    command: bundle exec sidekiq
    env_file: .env.docker.staging
    environment:
      - SERVICE_NAME=worker
    image: 023742962703.dkr.ecr.us-east-1.amazonaws.com/karma_backend_rails:test2
    logging:
      driver: awslogs
      options:
        awslogs-group: staging
        awslogs-region: us-east-1
        awslogs-stream-prefix: staging

```
ecs-params.yml:
```
version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: ecsTaskExecutionRole
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-0fff0d5d419f9b111"
        - "subnet-02fc15df22223e4c2"
        - "subnet-07ce2e735e29aa4f8"
      security_groups:
        - "sg-01e748fdbbc7312db"
      assign_public_ip: DISABLED

```
~/.ecs/config:
```
version: v1
default: karma-backend-staging
clusters:
  karma-backend-staging:
    cluster: karma-backend-staging
    region: us-east-1
    default_launch_type: FARGATE
```
