### ISSUE TITLE
Allow --create-log-groups when only some containers use CW Logs

### ISSUE THREAD

**Issue by PettitWesley** [aws/amazon-ecs-cli#642]
### Summary
The `--create-log-groups`requires that all containers are configured to use CloudWatch logs. It would be more useful if it worked when only some containers use CW Logs.

### Description
* Which specific command was run? 
```
$ ecs-cli compose service up --cluster-config kinesis-fargate --create-log-groups
INFO[0000] Using ECS task definition                     TaskDefinition="docker-amazon-kinesis-agent:6"
FATA[0000] Container 'apache' is not configured to use CloudWatch logs; logConfiguration ('logging' in Docker Compose) is a required container definition field 
```
* Which version of the CLI you are using? 
`v1.9.0`
* Which version of Go are you using? 
`go1.11.1`
* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows)
OS X

### Config files
* docker-compose.yml

```
version: '2'
services:
  kinesis-agent:
    image: ************.dkr.ecr.us-east-2.amazonaws.com/amazon-kinesis-agent:latest
    volumes:
      - shared_volume:/tmp/aws-kinesis-agent/
    logging:
      driver: awslogs
      options:
        awslogs-group: tutorial
        awslogs-region: us-east-2
        awslogs-stream-prefix: kinesis-agent
  apache:
    image: **********dkr.ecr.us-east-2.amazonaws.com/apache:latest
    volumes:
      - shared_volume:/var/log/apache
volumes:
  shared_volume:
```

Log Groups are successfully created when `apache` is given a CW Logs configuration.
