### ISSUE TITLE
"Invalid interpolation format" when specifying mandatory variables in docker-compose files

### ISSUE THREAD

**Issue by ptsteadman** [aws/amazon-ecs-cli#651]
### Summary
When using docker-compose v3 files that use [mandatory variable substition](https://docs.docker.com/compose/compose-file/#variable-substitution), running `ecs-cli compose` gives an "invalid interpolation format" error, even though syntax is valid for docker-compose v3. Possibly related to this project's docker-compose dependencies, see: https://github.com/docker/compose/issues/5683

### Description

* Which specific command was run? `ecs-cli compose -f ops/docker-compose.foo.yml -p foo create`
* Which version of the CLI you are using? `1.9.0`
* Which version of Go are you using? (Run: `go version`) `go not installed`
* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows) `ubuntu linux`

### Config files

* docker-compose.yml
```
version: '3'
services:
  isf-foo:
    image: "f00.dkr.ecr.us-east-1.amazonaws.com/isf-foo:${TAG:?err}"
    ports:
      - "9200:9200"
...
```
* ecs-params.yml

* ~/.ecs/config

### Observed Behavior

`ERRO[0000] Unable to open ECS Compose Project            error="invalid interpolation format for services.isf-foo.image: \"foo.dkr.ecr.us-east-1.amazonaws.com/isf-connector:${TAG:?err}\". You may need to escape any $ with another $.`
