### ISSUE TITLE
Unable to Copy nginx Config Into Container

### ISSUE THREAD

**Issue by davidbitton** [aws/amazon-ecs-cli#657]
### Summary
unable to copy config files

### Description
due to lack of sourcePath, I do not know how to copy my nginx config into the container

### Config files

* docker-compose.yml

```yaml
version: '3'

services:
  wordpress:
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - "./wordpress:/code"
      - "./site.conf:/etc/nginx/conf.d/default.conf"
    logging:
      driver: awslogs
      options:
        awslogs-group: mbp-ecs-cluster
        awslogs-region: us-east-1
        awslogs-stream-prefix: wordpress

  php:
    image: "newrelic:php"
    volumes:
      - "./wordpress:/code"
      - "./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf"
```

* ecs-params.yml

```yaml
version: 1
task_definition:
  task_execution_role: ecsTaskExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-X"
        - "subnet-X"
      security_groups:
        - "sg-X"
      assign_public_ip: ENABLED
```

* ~/.ecs/config

```yaml
version: v1
default: tutorial
clusters:
  mbp-ecs-cluster:
    cluster: mbp-ecs-cluster
    region: us-east-1
    default_launch_type: FARGATE
  tutorial:
    cluster: tutorial
    region: us-east-1
    default_launch_type: FARGATE
```

### Expected Behavior
copy nginx config into container

### Observed Behavior
>   ERRO[0000] Error registering task definition             error="ClientException: host.sourcePath should not be set for volumes in Fargate.\n\tstatus code: 400, request id: cdd9d0f2-dba9-11e8-ae52-63e23f75bf92"
