### ISSUE TITLE
Extension Fields

### ISSUE THREAD

**Issue by esetnik** [aws/amazon-ecs-cli#659]
### Summary

Does ecs-cli support docker-compose v3.4 extension fields syntax?

### Description

```
version: '3.4'

x-db-variables: &db-variables
    SQL_DATABASE: Test123
    SQL_HOST: test.com
    SQL_USER: test
    SQL_PASSWORD: test_pw
    SQL_PORT: 1433

services:
  frontend:
    build:
      context: ./frontend
    environment:
      <<: *db-variables
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app'
```
