### ISSUE TITLE
Task size not translated into web console?

### ISSUE THREAD

**Issue by codepushr** [aws/amazon-ecs-cli#696]
### Summary
When running a new task definition via CLI the task size settings aren't reflected (or even set?) in the web console.

### Description
Command used:
```
$ ecs-cli compose --file docker-compose-ecs.yml service up --force-deployment --cluster-config myconfig
```

### Config files
Params file:
```
version: 1
task_definition:
  # ecs_network_mode: awsvpc
  task_size:
    cpu: 896
    memory: 776
  services:
    service1:
      cpu_shares: 776
      mem_reservation: 256M
    service2:
      mem_reservation: 128M
    servicevolume:
      mem_reservation: 8M
      essential: false
    rabbitmq:
      mem_reservation: 128M
    redis:
      mem_reservation: 128M
    mongodb:
      mem_reservation: 128M
```

### Expected Behavior
The web console should reflect those limits in the task definition.

### Observed Behavior
![screen shot 2019-01-08 at 14 29 28](https://user-images.githubusercontent.com/1425202/50833560-d2b70800-1351-11e9-8fb8-4830cca04dce.png)
