### ISSUE TITLE
got error no declaration was found in the volumes section

### ISSUE THREAD

**Issue by wizardnet972** [aws/amazon-ecs-cli#698]
What is missing in my docker-compose.yml file?  I got an errror when I try to run a command with `ecs-cli`:

```
ecs-cli compose up --cluster tester-cluster

WARN[0000] Skipping unsupported YAML option for service...  option name=container_name service name=nginx-letsencrypt
WARN[0000] Skipping unsupported YAML option for service...  option name=restart service name=nginx-letsencrypt
ERRO[0000] Unable to open ECS Compose Project            error="named volume [C:\\_aws2\\docker-compose-letsencrypt-nginx-proxy-companion\\data\\conf.d] is used but no declaration was found in the volumes section"
FATA[0000] Unable to create and read ECS Compose Project  error="named volume [C:\\_aws2\\docker-compose-letsencrypt-nginx-proxy-companion\\data\\conf.d] is used but no declaration was found in the volumes section"
```

**docker-compose.yml**
```
version: '3'
services:
  nginx-web:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: ${NGINX_WEB:-nginx-web}
    restart: always
    ports:
      - "${IP:-0.0.0.0}:${DOCKER_HTTP:-80}:80"
      - "${IP:-0.0.0.0}:${DOCKER_HTTPS:-443}:443"
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
    logging:
      driver: ${NGINX_WEB_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_WEB_LOG_MAX_SIZE:-4m}
        max-file: ${NGINX_WEB_LOG_MAX_FILE:-10}

  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup ${NGINX_WEB:-nginx-web} -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: ${DOCKER_GEN:-nginx-gen}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:ro
      - ${NGINX_FILES_PATH:-./data}/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    logging:
      driver: ${NGINX_GEN_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_GEN_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_GEN_LOG_MAX_FILE:-10}

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ${LETS_ENCRYPT:-nginx-letsencrypt}
    restart: always
    volumes:
      - ${NGINX_FILES_PATH:-./data}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH:-./data}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH:-./data}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH:-./data}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: ${DOCKER_GEN:-nginx-gen}
      NGINX_PROXY_CONTAINER: ${NGINX_WEB:-nginx-web}
    logging:
      driver: ${NGINX_LETSENCRYPT_LOG_DRIVER:-json-file}
      options:
        max-size: ${NGINX_LETSENCRYPT_LOG_MAX_SIZE:-2m}
        max-file: ${NGINX_LETSENCRYPT_LOG_MAX_FILE:-10}

networks:
  default:
    external:
      name: ${NETWORK:-webproxy}
```

**Comment by PettitWesley** [comment]
@wizardnet972 Is `C:\\_aws2\\docker-compose-letsencrypt-nginx-proxy-companion\\data\\conf.d` the value of `$NGINX_FILES_PATH`? 

Is that a path on your local machine? That won't work with the ECS CLI, you can only mount directories from the EC2 instance that your container is running on. There are basically only 2 ways to use volumes in Compose with the ECS CLI:

Option 1: Mount host directory on EC2 instance
```
version: '2'
services:
  example:
    volumes:
      - /some_host_dir:/some_container_dir
``` 

This mounts `/some_host_dir` on the instance into your container at the path `/some_container_dir`.

Option 2: Named Volume (for scratch or for sharing between containers)
```
version: '2'
services:
  container1:
    volumes:
      - named_volume:/some_container_dir
  container2:
    volumes:
      - named_volume:/some_other_container_dir
volumes:
  - named_volume:
```
This creates an ephemeral, scratch volume which is shared between two containers.

Also note that you can create persistent Docker Volumes using the [ECS Params yaml file](https://github.com/aws/amazon-ecs-cli#using-ecs-parameters)!
