### ISSUE TITLE
Task_placement and constraints not read ?

### ISSUE THREAD

**Issue by gmembre-zenika** [aws/amazon-ecs-cli#701]
### Summary
I'm trying to deploy a service with placements and constraints definitions with docker-compose and ecs-params without success.

### Description

The service is created without the contraints I specified. If I look through the console, the constraints are not produced and the verbose mode of the ecs-cli confirms that it is not handled. But the documentation states that is is supported (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-ecsparams.html)

```
$ ecs-cli compose --verbose --file docker-compose.yml --cluster uat-api --project-name uat-persist-master service up --container-name persist --container-port 8080 --target-group-arn YYY
DEBU[0000] Parsing the compose yaml...
DEBU[0000] Docker Compose version found: 3
DEBU[0000] Parsing v3 project...
DEBU[0000] Parsing the ecs-params yaml...
DEBU[0000] Parsing the ecs-registry-creds yaml...
DEBU[0000] Transforming yaml to task definition...
DEBU[0000] Finding task definition in cache or creating if needed  TaskDefinition="{\n  ContainerDefinitions: [{\n      Command: [],\n      Cpu: 0,\n      DnsSearchDomains: [],\n      DnsServers: [],\n      DockerSecurityOptions: [],\n      EntryPoint: [],\n      Environment: [],\n      Essential: true,\n      ExtraHosts: [],\n      Image: \"XXXXX\",\n      Links: [],\n      LinuxParameters: {\n        Capabilities: {\n\n        },\n        Devices: []\n      },\n      Memory: 512,\n      MountPoints: [{\n          ContainerPath: \"/www\",\n          ReadOnly: false,\n          SourceVolume: \"env-volume\"\n        }],\n      Name: \"persist\",\n      PortMappings: [{\n          ContainerPort: 8080,\n          HostPort: 0,\n          Protocol: \"tcp\"\n        }],\n      Privileged: false,\n      ReadonlyRootFilesystem: false\n    }],\n  Cpu: \"\",\n  ExecutionRoleArn: \"\",\n  Family: \"uat-persist-master\",\n  Memory: \"\",\n  NetworkMode: \"\",\n  TaskRoleArn: \"\",\n  Volumes: [{\n      Name: \"env-volume\"\n    }]\n}"
...
```

I tried with 1.11.0 and 1.12.1 on OS X
```
$ ecs-cli -v
ecs-cli version 1.12.1 (e70f1b1)
```

Region : eu-west-3

### Config files
* docker-compose.yml
```
version: '3'
services:
  persist:
    image: XXXXXXX
    ports:
      - "0:8080"
```
* ecs-params.yml
```
version: 1
run_params:
  task_placement:
    constraints:
      - expression: attribute:ecs.instance-type =~ t2.*
        type: memberOf
```

### Expected Behavior

I expect that the definition task contains a section like this (through the console it works) : 
```
"placementConstraints": [
    {
      "type": "memberOf",
      "expression": "attribute:ecs.instance-type =~ t2.*"
    }
  ],
```

**Comment by SoManyHs** [comment]
Hi @gmembre-zenika,
Are you able to see your placement constraints if you call `describe-services` from the aws cli? Our current code path saves any task placement fields on the service itself, which should be visible on a describe call if you are using the `compose service up` command. Unfortunately these are not saved on the Task Definition associated with the service.

Could you let me know more about your workflow? Is persisting specific constraints on a Task Definition versus on the Service itself preferable in your use case?

**Comment by gmembre-zenika** [comment]
Thanks, this is perfect, the constraint is indeed placed on the service. 

Would you mind correcting the schema of ecs-params ? The description is lacking that type + field are list : 
```
  task_placement:
    strategy:
        type: string
        field: string
    constraints:
        type: string
        expression: string
```
should be : 
```
  task_placement:
    strategy:
       - type: string
          field: string
    constraints:
       - type: string
         expression: string
```
`minus sign` added in front of `type`.
