### ISSUE TITLE
Not able to resolve service names in network

### ISSUE THREAD

**Issue by al73rna** [aws/amazon-ecs-cli#708]
### Summary
using ecs-cli compose does not configure /etc/resolv.conf to enable cross container access. 
### Description
Using the following yml file, i am unable to ping the "app" container from within the proxy container.
The images are pretty barebones. "app" is a node 8.11.4 image and proxy is an "nginx" image. 
The issue is that the nginx service is not able to resolve the name "app". I am able to work around the issue by directly linking the services via adding the following to the proxy service:
```

    links:
      - app:app
```
Which will cause everything to work perfectly. However `links` is a deprecated feature in docker. I would like to know what's going wrong if possible.

I am deploying my containers to EC2 instances using the following command.
`ecs-cli compose -f docker-compose-ecs.yml up --cluster-config ec2-cluster`
### Config files
docker-compose-ecs.yml
```
services:
  app:
    environment:
      - NODE_ENV=production
    image: 043206754043.dkr.ecr.us-west-1.amazonaws.com/app:f24c4a0
  proxy:
    depends_on:
      - app
    image: 043206754043.dkr.ecr.us-west-1.amazonaws.com/proxy:f24c4a0
    ports:
      - 3001:80
    restart: unless-stopped

version: '3'

```

"app" dockerfile. 
```
FROM node:8.11.4

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . .
RUN yarn install
RUN yarn run build
EXPOSE 3000

CMD ["yarn", "run", "build:prod"]
```

"proxy" dockerfile
```
FROM nginx
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

```

nginx.conf
```
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    ##
    # Gzip Settings
    ##
    gzip on;
    gzip_http_version 1.1;
    gzip_disable      "MSIE [1-6]\.";
    gzip_min_length   1100;
    gzip_vary         on;
    gzip_proxied      any;
    gzip_types        text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_comp_level   9;

    location / {
        proxy_pass http://app:3000;
    }
}

```
ecs-params.yml
```
version: 1
task_definition:
  services:
    app:
      cpu_shares: 100
      mem_limit: 524288000
    proxy:
      cpu_shares: 100
      mem_limit: 524288000
```

### Expected Behavior
for ecs-cli compose to behave as close as possible to docker compose when it comes to resolving service names.
### Observed Behavior
When i run the same .yml file using docker compose, it will work fine. However using ecs-cli compose will result in an error from the "proxy" service not being able to resolve the "app" service:

> nginx: [emerg] host not found in upstream

As i mentioned, the issue will be fixed if i add a link to the proxy service like this:
```
    links:
      - app:app
```
