### ISSUE TITLE
Environment variables not read from .env file for for compose 3

### ISSUE THREAD

**Issue by allisaurus** [aws/amazon-ecs-cli#726]
### Summary
Per [this example](https://github.com/aws/amazon-ecs-cli/issues/537#issuecomment-463146433), environment variables defined in an .env file are not read into docker-compose.yml files using compose version 3.

### Description

v2 docker-compose file:

```
version: '2'
services:
  tracker:
    image: X/image:$TAG
```
RESULT: `TAG` read in

v3 docker-compose file:

```
version: '3'
services:
  tracker:
    image: X/image:$TAG
```
RESULT: `TAG` NOT read in

### Expected Behavior
Vars defined in .env would be interpolated into `docker-compose.yml` for both compose versions.

### Observed Behavior
Only v2 compose projects correctly interpolate vars defined in .env
