### ISSUE TITLE
ecs-cli does not parse a service mem_* values in ecs-params.yml

### ISSUE THREAD

**Issue by toredash** [aws/amazon-ecs-cli#727]
### Summary
ecs-cli does not use mem_limit and mem_reservation values in ecs-params.yml

This generates unexpected generated task definition content in ECS.

ecs-cli v.1.12.1 is used.

### Description
Given the ecs-params.yml file:
```
version: 1
task_definition:
  task_size: 
    cpu_limit: 256
    mem_limit: 512
  services:
    ui:
      essential: true
      cpu_shares: 256
      mem_limit: 512
      mem_reservation: 128
```

The resulting task definition does not contain any container-level hard/soft limit of memory:
```
      "memory": null,
      "memoryReservation": null,
```

### Config files
Not relevant.

### Expected Behavior
I'm expecting the containerDefinition in the task definition json file to contain:
```
      "memory": 512,
      "memoryReservation": 128,
```

### Observed Behavior
The containerDefinition in the task definition json file to contain:
```
      "memory": null,
      "memoryReservation": null,
```

PS: ecs-cli `v1.12.0` creates a task definition with the mem_limit field set:
```
            "memory": 512,
            "memoryReservation": null,
```

So I can only assume some breaking changes was introduced at some point
