### ISSUE TITLE
Unable to assume the service linked role when following the fargate tutorial

### ISSUE THREAD

**Issue by maltzj** [aws/amazon-ecs-cli#733]
### Summary

I'm attempting to follow the Fargate deployment tutorial but I'm getting an error about being unable to assume a service linked role.

### Description

I'm attempting to follow the [ecs-cli Fargate deployment tutorial](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-fargate.html) and have hit a problem attempting to deploy my service.

I am attempting to deploy my test container using `ecs-cli compose --project-name tutorial-maltz service up` but I am getting an error which says `"InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.\n\tstatus code: 400, request id`

So far I have created my IAM permission using the steps provided, and have verified that I have an IAM role `ecsTaskExecutionRole` which contains an `AmazonECSTaskExecutionRolePolicy`. This policy also has a trust relationship which looks like the following:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
All of this is being deployed off of a ecs-params.yml file which looks like the following:

* Which version of the CLI you are using? 1.2.1
* Which version of Go are you using? (Run: `go version`) go version go1.11.1 darwin/amd64
* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows) osx

### Config files

* docker-compose.yml

```
version: '3'
services:
    wordpress:
        image: wordpress
        ports:
            - "80:80"
```

* ecs-params.yml

```
version: 1
task_definition:
    task_execution_role: ecsTaskExecutionRole
    ecs_network_mode: awsvpc
    task_size:
        mem_limit: 0.5GB
        cpu_limit: 256
run_params:
    network_configuration:
        awsvpc_configuration:
            subnets:
                - "subnet-from-ecs-cli-up"
            security_groups:
                - "subnet-created-by-ecs-cli-up"
        assign_public_ip: ENABLED
```

* ~/.ecs/config

```
version: v1
default: maltz-test-config
clusters:
  default:
    cluster: tutorial-maltz
    region: us-west-2
    default_launch_type: FARGATE
  maltz-test-config:
    cluster: tutorial-maltz
    region: us-west-2
    default_launch_type: FARGATE
  tutorial-maltz:
    cluster: tutorial-maltz
    region: us-west-2
    default_launch_type: FARGATE
```

### Expected Behavior

I'd expect that I can stand up my service

### Observed Behavior

```
INFO[0000] Using ECS task definition                     TaskDefinition="tutorial-maltz:3"
ERRO[0000] Error creating service                        error="InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.\n\tstatus code: 400, request id: 4a2969a9-3a30-11e9-a9dc-13c641ab2d7f" service=tutorial-maltz
INFO[0000] Created an ECS service                        service=tutorial-maltz taskDefinition="tutorial-maltz:3"
FATA[0000] InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
	status code: 400, request id: 4a2969a9-3a30-11e9-a9dc-13c641ab2d7f
```
