### ISSUE TITLE
Error `Failed to initialize logging driver` occurred when specify logging driver awslogs

### ISSUE THREAD

**Issue by kodomo898** [aws/amazon-ecs-cli#752]
### Summary

When ecs-clis specified ecs-params.yml / docker-compose.yml and executed, the following error occurred.

**CannotStartContainerError: Error response from daemon: failed to initialize logging driver: CredentialsEndpointError: failed to load credentials caused by: RequestError: send request failed caused by: Get http://169.254.170.2/v2/credentials/ //container-id//**

http://169.254.170.2/v2/ can only be used in awsvpc mode

but

I want to set the container’s PORT as random.

### Description
I implemented the following command

`platform: MacOS`

`ecs-cli compose --debug service --cluster app-staging up`

### Config files
* docker-compose.yml

```
version: '2'
services:
  app:
    image: <image>
    command: bundle exec puma -e production -C config/puma.rb
    env_file:
      - .env.app.staging
    working_dir: /projects/app

    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "app-staging/test-app"
        awslogs-stream-prefix: "app"

  nginx:
    image: <image>
    entrypoint:
      - /bin/bash
      - /etc/nginx/start.sh
    ports:
      - 0:80
    links:
      - "app:app"
    env_file:
      - .env.nginx.staging
    working_dir: /projects/nginx

    logging:
      driver: "awslogs"
      options:
        awslogs-region: "ap-northeast-1"
        awslogs-group: "nginx-staging/nginx"
        awslogs-stream-prefix: "nginx"

```

* ecs-params.yml

```
version: 1
task_definition:
  ecs_network_mode: bridge
  task_role: ecsServiceTaskRole
  task_execution_role: ecsServiceTaskRole
  services:
    coda-app:
      essential: true
      secrets:
         - value_from: /app-staging/SECRET_KEY_BASE
           name: SECRET_KEY_BASE

    coda-nginx:
      essential: true
  run_params:
    network_configuration:
      awsvpc_configuration:
        subnets:
          - <subnet>
        security_groups:
          - <sg>
```

* ~/.ecs/config

```
version: v1
default: app-staging
clusters:
  app-staging:
    cluster: app-staging
    region: ap-northeast-1
    default_launch_type: ""
```
