### ISSUE TITLE
ecs compose not surpport for expose port container?

### ISSUE THREAD

**Issue by RodrigoBCC** [aws/amazon-ecs-cli#768]
Cannot make nginx and django on ecs containers using compose and ecs-cli

The problem is: In my local machine i use "expose"(Ok), but it's not support ecs-cli and when up the container on ecs, the container have no ports and "expose" are not supported to ecs-cli compose. So, i cannot up my application with nginx server?
When i use "virtual port" crashes my container, its normal? or dont haver support for that?
### Config files

*docker-compose.yml
```
version: "2"
services:
  flower:
    command: ["flower", "--broker=redis://redis:6379/0", "--port=5555"]  
    environment:
      - "VIRTUAL_HOST=example.com"
      - "VIRTUAL_PORT=5555"
    image: mher/flower
    links:
      - redis
    mem_limit: 126m
    cpu_shares: 126
  nginx:
    image: my_image/nginx:latest
    mem_limit: 126m
    cpu_shares: 126
    ports:
      - 5555:5555
      - 8000:8000
      - 80:8000
    links:
      - django
      - flower
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    mem_limit: 126m
    cpu_shares: 126
  celery:
    image: my_image:latest
    command: bash -c "celery -A litoteca worker -l info"
    mem_limit: 126m
    cpu_shares: 126
    links:
      - redis
  django:
    command: bash -c "./server_run.sh"
    environment:
      - "VIRTUAL_HOST=example.com"
      - "VIRTUAL_PORT=8000"
    expose:
      - "8000"
    image: my_image:latest
    cpu_shares: 512
    mem_limit: 512m
    links:
      - redis
```
