### ISSUE TITLE
CannotStartContainerError - executable file not found in $PATH

### ISSUE THREAD

**Issue by aaronfranco** [aws/amazon-ecs-cli#78]
Hi,

I'm trying to get my NodeJS service running on AWS using Docker Compose with the ECS-CLI tools from Amazon. I get the following error on every container attempting to run.

````
STOPPED Reason: CannotStartContainerError: API error (500): Cannot start container 54b6caa1f3d8476a7b3538827d4d5017596d696b0877925d1d28a9de735b2433: [8] System error: exec: "node index.js -t sockets_transport -i 0": executable file not found in $PATH
````

The docker-compose file looks like the following:

````
octopusws:
  net: host
  image: telepat/octopusworker:0.2.3
  # image: octopus-worker-test
  command: node index.js -t sockets_transport -i 0
````
Any idea what is happening here? I can't seem to find any useful information on this error. Any help would be greatly appreciated. 

Best,
aaron
