### ISSUE TITLE
Support docker-compose version 3.4+ to leverage multi-stage builds

### ISSUE THREAD

**Issue by rybakit** [aws/amazon-ecs-cli#781]
### Summary
Currently, `ecs-cli` only supports major docker compose versions, like 2.0, 3.0. However, version 3.4 introduced [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/) which allows building complex but efficient images within a singe Dockerfile. It would be greate if `ecs-cli` could support this feature.

### Description
* Which specific command was run?
```
ecs-cli compose --project-name foobar service up --create-log-groups --cluster-config foobar
```

* Which version of the CLI you are using?
```
ecs-cli version 1.14.1 (f73f9e3)
```

* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows)

Linux

### Config files
* docker-compose.yml

```yaml
version: '3.4'

services:
  api:
    image: ${CONTAINER_REGISTRY_BASE}/foobar:${CONTAINER_REGISTRY_VERSION}
    build:
      context: ./foobar
      target: foobar_nginx
    ports:
      - "80:80"
    logging:
      driver: awslogs
      options:
        awslogs-group: foobar
        awslogs-region: eu-central-1
        awslogs-stream-prefix: foobar
```

### Expected Behavior

The command succeeds without errors.

### Observed Behavior

The command fails with:

```
ERRO[0000] Unable to open ECS Compose Project            error="Unsupported Docker Compose version found: 3.4"                                                                                                                                
FATA[0000] Unable to create and read ECS Compose Project  error="Unsupported Docker Compose version found: 3.4"   
```
