### ISSUE TITLE
Field `awslogs-stream-prefix` not supported by ECS local

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli#800]
## Summary

The `awslogs-stream-prefix` field defined [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html) is not available under the [Docker Amazon CloudWatch log options](https://docs.docker.com/config/containers/logging/awslogs/#amazon-cloudwatch-logs-options). So `local up` fails with the following error:
```
ERROR: for local-cmds_nginx_1  Cannot create container for service nginx: unknown log opt 'awslogs-stream-prefix' for awslogs log driver

ERROR: for nginx  Cannot create container for service nginx: unknown log opt 'awslogs-stream-prefix' for awslogs log driver
ERROR: Encountered errors while bringing up the project.
```
Can we just remove that field for ECS local? or alternatively look into mimicking the functionality with `prefix-name/container-name/ecs-task-id`?

**Comment by efekarakus** [comment]
Here is my task definition for reference:
```json
{
    "taskDefinition": {
        "taskDefinitionArn": "arn:aws:ecs:us-east-1:111111111:task-definition/TaskForECSLocalWithSecrets:1",
        "containerDefinitions": [
            {
                "name": "nginx",
                "image": "nginx",
                "cpu": 0,
                "portMappings": [
                    {
                        "containerPort": 3000,
                        "hostPort": 3000,
                        "protocol": "tcp"
                    }
                ],
                "essential": true,
                "environment": [],
                "mountPoints": [],
                "volumesFrom": [],
                "secrets": [
                    {
                        "name": "TestSecret1",
                        "valueFrom": "arn:aws:secretsmanager:us-east-1:1111111111:secret:MYSECRET"
                    }
                ],
                "logConfiguration": {
                    "logDriver": "awslogs",
                    "options": {
                        "awslogs-group": "/ecs/TaskForECSLocalWithSecrets",
                        "awslogs-region": "us-east-1",
                        "awslogs-stream-prefix": "ecs"
                    }
                }
            }
        ],
        "family": "TaskForECSLocalWithSecrets",
        "executionRoleArn": "arn:aws:iam::111111111111:role/ecsTaskExecutionRole",
        "networkMode": "awsvpc",
        "revision": 1,
        "volumes": [],
        "status": "ACTIVE",
        "requiresAttributes": [
            {
                "name": "ecs.capability.secrets.asm.environment-variables"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.18"
            },
            {
                "name": "ecs.capability.task-eni"
            },
            {
                "name": "ecs.capability.execution-role-awslogs"
            },
            {
                "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
            },
            {
                "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19"
            }
        ],
        "placementConstraints": [],
        "compatibilities": [
            "EC2",
            "FARGATE"
        ],
        "requiresCompatibilities": [
            "FARGATE"
        ],
        "cpu": "256",
        "memory": "512"
    }
}
```

and the output from `local create`:
```yml
version: "3.0"
services:
  nginx:
    environment:
      TestSecret1: ${TestSecret1}
    image: nginx
    labels:
      ecs-local.secret.TestSecret1: arn:aws:secretsmanager:us-east-1:1111111111:secret:MYSECRET
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/TaskForECSLocalWithSecrets
        awslogs-region: us-east-1
        awslogs-stream-prefix: ecs
```
