### ISSUE TITLE
Change network of local containers to "ecs-local-network"

### ISSUE THREAD

**Issue by efekarakus** [aws/amazon-ecs-cli#802]
## Summary

The current version of [ConvertToDockerCompose()](https://github.com/aws/amazon-ecs-cli/blob/86efe885e24d15d82bc4bf0c034c9f54a282cb9b/ecs-cli/modules/cli/local/converter/converter.go#L61) doesn't set the network of the containers to `ecs-local-network`.

We want to have the network of the containers set to the external `ecs-local-network`.  
So that the containers can talk with the `LocalEndpointsContainer` container.

### Programming Model
The Compose file should look like:
```yml
version: "3"
networks:
  ecs-local-network:
    external: true
services:
  serviceA:
    networks: 
    - ecs-local-network
```

### Acceptance Criteria
1. Once we run `local up` on the Compose file, `docker exec CONTAINER_ID curl 169.254.170.2/v3/stats | jq` should return results
