### ISSUE TITLE
Local up: Error parsing docker compose

### ISSUE THREAD

**Issue by SoManyHs** [aws/amazon-ecs-cli#825]
docker compose file:
```
version: "3.0"
services:
  httpd:
    environment:
      TEST: DEMO1
      devx-test: woo-hoo!
      foo: bar
    image: httpd:2.4
    labels:
      ecs-local.task.type: localFile
      ecs-local.task.value: ""
    networks:
      ecs-local-network: null
networks:
  ecs-local-network:
    external: true
```
```$ ecs-cli local up -f docker-compose.yml 
FATA[0000] Error with local create: Error parsing task definition JSON: invalid character 'v' looking for beginning of value
