### ISSUE TITLE
ecs-cli local: need to use override files

### ISSUE THREAD

**Issue by clareliguori** [aws/amazon-ecs-cli#831]
Two important use cases for ecs-cli local are:
* I want to build from a local Dockerfile when starting my local containers
* I want to start additional containers that I only need locally, for example a local mysql container or dynamodb-local

If I have something like docker-compose.local.override.yml with the following, I would expect ecs-cli local to merge the files so that I get my mysql container and the bot container is built from source.
```
version: "3.0"
services:
  bot:
    build: .
  db:
    image: mysql:5.7.4
```

Example behavior I'm expecting:
```
docker-compose -f docker-compose.local.yml -f docker-compose.local.override.yml up --build
```

**Comment by clareliguori** [comment]
The docker-compose.local.yml that I'm working from;
```
version: "3.0"
services:
  bot:
    environment:
      botUser: clare-bot
      githubToken: ${bot_githubToken}
      whitelistedUsers: clareliguori
    image: 131296546870.dkr.ecr.us-west-2.amazonaws.com/clare-bot:latest
    labels:
      ecs-local.secret.githubToken: arn:aws:ssm:us-west-2:131296546870:parameter/clare-bot-github-token
      ecs-local.task.type: localFile
      ecs-local.task.value: ./task-def-local.json
    networks:
      ecs-local-network: null
networks:
  ecs-local-network:
    external: true
```

**Comment by efekarakus** [comment]
With the proposed commands and flags in https://github.com/aws/amazon-ecs-cli/issues/809, this would translate to:

```shell
$ ecs-cli local up -c docker-compose.local.yml -c docker-compose.local.override.yml
```
`-c` is short for `--task-def-compose`: the Compose file name of a task definition to run.

Does that sound good to you @clareliguori ?

**Comment by clareliguori** [comment]
Can I use `ecs-cli local up -f my-task-def.json -c docker-compose.local.override.yml`? Or do I have to use `local create` in order to create docker-compose.local.yml first.

**Comment by SoManyHs** [comment]
Based on yesterday's discussion, we are going to add an `--overrides` flag that will take docker compose `*.ecs-local.override.yml` files. If the override flag is not specified, `up` will automatically pick up any file with the same name as the docker compose file generated from the up command (default: docker-compose.ecs-local.override.yml)

**Comment by efekarakus** [comment]
# Proposal
We will introduce a new flag `--compose-override, -co` to specify a list of Compose files to use as overrides. Please especially evaluate the **note** sections.

## `local create`

This command will not support `-co`. However, the following changes will be made to the command

### Create also a default override file

By default `local create` will create two files: `docker-compose.ecs-local.yml` ([PR#847](https://github.com/aws/amazon-ecs-cli/pull/847)) and `docker-compose.ecs-local.override.yml`.

### Create a custom override file

If the user specified a custom output name with `--output name`, then we will create `{name without extension}.override.yml`.

### Content of override file

The generated override file will have the following content for all services by default:

```yaml
<serviceName>:
	environment:
		AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: "/creds"
	logging:
		driver: "none"
```

## `local up`

### With `--task-def-file`, `--task-def-remote `, or no flags

All three of these use-cases result in the creation of  `docker-compose.ecs-local.yml` and `docker-compose.ecs-local.override.yml`. 

Before starting the containers we will search if  `docker-compose.ecs-local.override.yml` exists, if yes then the override file will be used.

### With `--task-def-compose name` 

By default we will search if `{name without extension}.override.yml` exists, if so we will use that. 

**Note**: If the user chose `--task-def-compose` as their input then  `docker-compose.ecs-local.override.yml` will be ignored. We will only search for  `{name without extension}.override.yml` .

### With `--compose-override name, -co name`

The user will be able to choose any single input flag of their like `-c`, `-f` , `-r` or none but they can specify multiple `-co` flags.

The `-co` flag results in appending additional Compose files:

- If the `--output` flag is not set, for example: `ecs-cli local up -r MyAPIFamily -co db.override.yml -co api.override.yml` then this will translate into `docker-compose -f docker-compose.ecs-local.yml -f docker-compose.ecs-local.override.yml -f db.override.yml -f api.override.yml --build`
- If the `—-output` flag is set, then it's the same as above but the default base file and override Compose files have the custom names instead.

**Note**: As far as I can tell, this is a bit different than the way `docker-compose` works, `docker-compose` ignores their default base and override files if `-f` is provided:

> To deploy with this production Compose file you can run
>
> ```
> docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
> ```
>
> This deploys all three services using the configuration in `docker-compose.yml` and `docker-compose.prod.yml` (but not the dev configuration in `docker-compose.override.yml`).

https://docs.docker.com/compose/extends/#example-use-case
