### ISSUE TITLE
"ecs-cli local up" error on Windows: cannot create temporary directory!

### ISSUE THREAD

**Issue by allisaurus** [aws/amazon-ecs-cli#892]
### Summary
While running `ecs-cli local up` on my Windows machine I get an error at the point when containers are attempting to start. 

### Description
* Which specific command was run? 
`ecs-cli local up`

* Which version of the CLI you are using?
1.15.1
* Which version of Go are you using? (Run: `go version`)
N/A

* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows)
Windows

### Config files

* task-definition.json
```
{
    "containerDefinitions": [
        {
            "name": "httpd",
            "image": "httpd:2.4",
            "essential": true,
            "portMappings": [],
            "environment": [
                {"name": "foo", "value": "bar"},
                {"name": "TEST", "value": "DEMO1"}
            ]
        }
    ],
    "requiresCompatibilities": [
        "FARGATE"
    ],
    "networkMode": "awsvpc",
    "executionRoleArn": "ecsExecutionRole",
    "cpu": "256",
    "memory": "512",
    "family": "httpd"
}
```

* docker-compose.ecs-local.yml
```
version: "3.4"
services:
  httpd:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
      TEST: DEMO1
      devx-test: woo-hoo!
      foo: bar
    image: httpd:2.4
    labels:
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: [REDACT]\LOCAL\2.0\my-task-definition.json
    networks:
      ecs-local-network: null
networks:
  ecs-local-network:
    external: true
```

* docker-compose.ecs-local.override.yml
```
version: "3.4"
services:
  httpd:
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
    logging:
      driver: json-file
```

### Expected Behavior
The containers would start and be visible with `ecs-cli local ps`

### Observed Behavior
```
PS ~\ecs-cli\LOCAL\2.0> .\ecs-cli.exe local up
[36mINFO[0m[0000] The network ecs-local-network already exists
[36mINFO[0m[0000] The amazon-ecs-local-container-endpoints container already exists with ID d64862974635b39b8b673d5a8058c5a66624b7af8e21254806452f43f4811129
[36mINFO[0m[0000] Started container with ID d64862974635b39b8b673d5a8058c5a66624b7af8e21254806452f43f4811129
[36mINFO[0m[0000] Using docker-compose.ecs-local.yml, docker-compose.ecs-local.override.yml files to start containers
[10876] INTERNAL ERROR: cannot create temporary directory!
[31mFATA[0m[0000] docker-compose up failed to exit successfully due to:
exit status 4294967295
```
