### ISSUE TITLE
Mapping for depends_on and ContainerDependency

### ISSUE THREAD

**Issue by dkovvuri** [aws/amazon-ecs-cli#897]
### Support transformation of [depends_on](https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on) in Docker Compose to [ContainerDependency](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definition_dependson) objects in the ECS task definition.

ECS has recently announced support for [container dependency](https://aws.amazon.com/about-aws/whats-new/2019/03/amazon-ecs-introduces-enhanced-container-dependency-management/) within a task. When using the ecs-cli to transform a docker-compose file to an ECS task definition the options ***depends_on*** are skipped with the error:

>WARN[0000] Skipping unsupported YAML option for service...  option name=depends_on service name=webserver

#### Steps to Replicate

I. Docker-Compose File

```
version: '2'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow

    webserver:
        image: puckel/docker-airflow:1.10.3
        restart: always
        links:
            - postgres
            - redis
        depends_on:
            - postgres
            - redis
        ports:
            - "8080:8080"
        command: webserver
```

II. Run `ecs-cli`

```
ecs-cli compose --file compose.yml --project-name test run --region us-east-1
```
