### ISSUE TITLE
`ecs-cli compose service up` instant response

### ISSUE THREAD

**Issue by NikitaGl** [aws/amazon-ecs-cli#898]
### Summary

We are using `ecs-cli` in our CD pipeline and sometimes (with no consistent pattern) our jobs are completed instantly with success, while deployment is still in process. I'm not sure if this is cli related issue or API, but since this issue happens occasionally I can't verify it manually.
### Description

* Which specific command was run? 
```ecs-cli compose --cluster-config <config_name> --project-name <project_name> service up --force-deployment --target-group-arn <arn> --container-name <name> --container-port <port>```
* Which version of the CLI you are using?
```ecs-cli version 1.14.1 (f73f9e3)```
* Which version of Go are you using?
golang is absent on runner machine
* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows)
Amazon Linux 2
### Config files

* docker-compose.yml
```
version: '2'

services:

    nginx:
      image: imagename:tag
      ports:
        - '80:80'
      volumes_from:
        - php-fpm:ro
      logging:
        driver: "awslogs"
        options:
          awslogs-region: "us-west-2"
          awslogs-group: "/ecs/appname-${ENV}"
          awslogs-stream-prefix: "NGINX"

    php-fpm:
      image: "imagename:tag"
      environment:
        - "ENVIRONMENT=${ENV}"
        - APPLICATION=appname
        - AWS_REGION=us-west-2
      logging:
        driver: "awslogs"
        options:
          awslogs-region: "us-west-2"
          awslogs-group: "/ecs/appname-${ENV}"
          awslogs-stream-prefix: "PHP"

```
* ecs-params.yml
```
version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_role_arn: arn:aws:iam::accnum:role/rolename
  task_execution_role: arn:aws:iam::accnum:role/rolename
  task_size:
    mem_limit: 2048
    cpu_limit: 512
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-id"
      security_groups:
        - "sg-id"
```
* ~/.ecs/config
```
version: v1
default: clustername
clusters:
  clustername:
    cluster: clustername
    region: us-west-2
    default_launch_type: FARGATE
```

### Expected Behavior
`ecs-cli` will guide through all deployment steps, which are: registering new taskdef version, service update, task start, register it in target group, deregister old task, drain them, stop them, report stable state. 
### Observed Behavior

```
ecs-cli compose --cluster-config <conf_name> --project-name <project_name> service up --force-deployment --target-group-arn <arn> --container-name <name> --container-port <port>
time="2019-07-30T12:48:13Z" level=info msg="Using ECS task definition" TaskDefinition="taskdefname:139"
time="2019-07-30T12:48:13Z" level=warning msg="You cannot update the load balancer configuration on an existing service." serviceName=servicename
time="2019-07-30T12:48:13Z" level=info msg="Updated the ECS service with a new task definition. Old containers will be stopped automatically, and replaced with new ones" desiredCount=3 force-deployment=true service=servicename
time="2019-07-30T12:48:13Z" level=info msg="Service status" desiredCount=3 runningCount=3 serviceName=servicename
time="2019-07-30T12:48:13Z" level=info msg="ECS Service has reached a stable state" desiredCount=3 runningCount=3 serviceName=servicename
```
**P.S.**
Almost same happens at first launch of service through ecs-cli, but it just don't wait for initial registration of ecs task in target group. But it is a different story, not dangerous for production usage.
