### ISSUE TITLE
ecs-cli unable to retrieve credentials from either aws profile or ecs profile

### ISSUE THREAD

**Issue by dramaticlly** [aws/amazon-ecs-cli#929]
#### Summary
ecs-cli unable to retrieve credentials from either aws profile or ecs profile with NoCredentialProviders error 

I have a default AWS profile named "ci" which work in traditional aws cli but not in ecs-cli given ecs-cli somehow don't know where to retrieve credential 

### working aws profile (able to list clusters)
```
echo $AWS_PROFILE                                                                                                     
ci
```
```
aws configure --profile $AWS_PROFILE list   
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile                       ci           manual    --profile
access_key     ****************QKAT         isengard
secret_key     ****************Hvrf         isengard
    region           ap-northeast-1      config-file    ~/.aws/config
```
```
aws --profile ci ecs list-clusters                                                                                    
{
    "clusterArns": [
        "arn:aws:ecs:ap-northeast-1:388892025991:cluster/fargate-demo-ECSCluster-18NYFKXKPB240"
    ]
}
```

## ecs profile with same creds
```
cat ~/.ecs/credentials                                                                                                
version: ""
default: ci
ecs_profiles:
  ci:
    aws_access_key_id: ****************
    aws_secret_access_key: ****************
```

## ecs-cli up never works 
```
% ecs-cli up --empty                
ERRO[0000] Failed to Create Cluster   cluster=fargate-demo-ECSCluster-18NYFKXKPB240 
error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
FATA[0000] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

% ecs-cli up --aws-profile ci --empty --verbose  
ERRO[0000] Failed to Create Cluster     cluster=fargate-demo-ECSCluster-18NYFKXKPB240 error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseE
rrors"
FATA[0000] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors

% ecs-cli up --ecs-profile ci --empty --verbose 
ERRO[0000] Failed to Create Cluster      cluster=fargate-demo-ECSCluster-18NYFKXKPB240 error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseE
rrors"
FATA[0000] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

#### Description

* Which specific command was run? `ecs-cli up --empty`
* Which version of the CLI you are using? (ecs-cli version 1.16.0 (5c02c34))
* Which version of Go are you using? (Run: `go version`)
N/A, why do we have to care about underlying go environment if we are actively develop in go? It should come with binaries by default. I don't have explicit go env installed
* What platform are you using to run ECS CLI commands? (Amazon linux)

#### Config files

I DON'T think these matters but here it is anyway
* docker-compose.yml
```
version: '3'
services:
  ecsdemo-frontend:
    environment:
      - CRYSTAL_URL=http://ecsdemo-crystal.service:3000/crystal
      - NODEJS_URL=http://ecsdemo-nodejs.service:3000
    image: brentley/ecsdemo-frontend
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
        awslogs-group: ecsdemo-frontend
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecsdemo-frontend
```
* ecs-params.yml
```
version: 1
task_definition:
  task_execution_role: arn:aws:iam::388892025991:role/fargate-demo-ECSTaskExecutionRole-89DHZDXF8L64
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-008f3e5bba5953b7d"
        - "subnet-0edb5bf08b0ec58c7"
        - "subnet-0628761f4895e6371"
      security_groups:
        - "sg-0af14332494b2f96f"
      assign_public_ip: DISABLED
```
* ~/.ecs/config
```
version: v1
default: fargate-demo
clusters:
  fargate-demo:
    cluster: fargate-demo-ECSCluster-18NYFKXKPB240
    region: ap-northeast-1
    default_launch_type: FARGATE
```

#### Expected Behavior
created cluster given crendentials
#### Observed Behavior
ERRO[0000] Failed to Create Cluster   cluster=***
error="NoCredentialProviders: no valid providers in chain. Deprecated.\n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
FATA[0000] Error executing 'up': NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
