### ISSUE TITLE
Task definition cache is non-deterministic due to env var ordering

### ISSUE THREAD

**Issue by csw** [aws/amazon-ecs-cli#930]
#### Summary

When using the ecs-cli compose functionality, the task definition cache is not effective; repeated `ecs-cli compose create` invocations create new task definitions. This is because environment variable ordering in the task definitions is non-deterministic, resulting in cache misses.

#### Description

On version 1.16.0, 5c02c34, with a release binary on Linux, I ran the command:
    ecs-cli compose --verbose create --region us-west-2 --cluster support-jobs --launch-type FARGATE --tags Owner=csw

#248 made task definition caching deterministic, but the ordering of environment variables in the internal representation here changes from run to run. It's not clear to me whether this is a regression or simply something that wasn't addressed in that PR.

Note that in my docker-compose.yml, the environment variables are given as an array, not a map, so this non-determinism would presumably be introduced after YAML parsing. I've looked through the code briefly, and I don't see an obvious cause; the environment variables seem to be kept as arrays of key-value pairs. Maybe this is occurring in external code, the AWS SDK or the Docker Compose libraries?

#### Config files

docker-compose.yml:

```
version: '3'
services:
  test:
    image: ubuntu:bionic
    environment:
      - A=123
      - B=234
      - C=345
```

ecs-params.yml:
```

version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_role_arn: arn:aws:iam::807716841023:role/apps/prod/xxxxxx
  task_execution_role: ecsTaskExecutionRole
  task_size:
    cpu_limit: 4096
    mem_limit: 30720
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-xxxxx
      security_groups:
        - sg-xxxxxx
        - sg-yyyyyy
      assign_public_ip: ENABLED
```

~/.ecs/config:
```
version: v1
default: default
clusters:
  default:
    cluster: mycluster
    region: us-west-2
    default_launch_type: FARGATE
```

#### Expected Behavior

Repeated invocations of `ecs-cli compose create` with the same files result in cache hits and no new task definitions are created.

#### Observed Behavior

Running that command several times results in cache misses and the creation of new task definition versions.

From the log:
````
DEBU[0000] Finding task definition in cache or creating if needed  TaskDefinition="{\n  ContainerDefinitions: [{\n      Command: [],\n      Cpu: 0,\n      DnsSearchDomains: [],\n      DnsServers: [],\n      DockerSecurityOptions: [],\n      EntryPoint: [],\n      Environment: [{\n          Name: \"B\",\n          Value: \"234\"\n        },{\n          Name: \"C\",\n          Value: \"345\"\n        },{\n          Name: \"A\",\n          Value: \"123\"\n        }],\n      Essential: true,\n      ExtraHosts: [],\n      Image: \"ubuntu:bionic\",\n      Links: [],\n      LinuxParameters: {\n        Capabilities: {\n\n        },\n        Devices: []\n      },\n      Name: \"test\",\n      Privileged: false,\n      PseudoTerminal: false,\n      ReadonlyRootFilesystem: false\n    }],\n  Cpu: \"4096\",\n  ExecutionRoleArn: \"ecsTaskExecutionRole\",\n  Family: \"ecs_cache_test\",\n  Memory: \"30720\",\n  NetworkMode: \"awsvpc\",\n  RequiresCompatibilities: [\"FARGATE\"],\n  TaskRoleArn: \"arn:aws:iam::807716841023:role/apps/prod/cvr-reporting\",\n  Volumes: []\n}"
DEBU[0000] cache miss                                    taskDef="{\n\n}" taskDefHash=1065b0eac2ed1c1ae292d169d9dae
````
Observe that the environment variables are in the order B, C, A; in the previous run they were A, B, C.
