### ISSUE TITLE
warning not relevant: Skipping unsupported YAML option for service... option name=build

### ISSUE THREAD

**Issue by diablodale** [aws/amazon-ecs-cli#932]
#### Summary
`ecs-cli compose service up`, `ecs-cli compose create`, and perhaps other commands used with service in `docker-compose.yml`  having `build` section, causes irrelevant warning to appear
```
WARN[0000] Skipping unsupported YAML option for service...  option name=build service name=myservice
```
This warning is not relevant to the command `compose service up` or `ecs-cli compose create`. Only warnings that are relevant to the command being used should appear. As in life, the context in which a communication occurs is of most importance. It is distracting to provide warning feedback when the context has nothing to do with the warning.

#### Setup

Ubuntu 18.04.3 LTS on x86_64
ecs-cli version 1.16.0 (5c02c34)
GO is not installed.

#### Config files

docker-compose.yml
```
version: '2'
services:
  myservice:
    build:
      context: .
      dockerfile: myservice.dockerfile
    image: myservice
    read_only: true
    hostname: myservice
```

ecs-params.yml
```
(blank)
```

#### Expected Behavior

No warnings about a `build` section. Since ecs-cli does not support a `build` command, then this warning should never appear in any scenario of ecs-cli.

#### Observed Behavior

```
WARN[0000] Skipping unsupported YAML option for service...  option name=build service name=myservice
```
