### ISSUE TITLE
ecs-cli compose fails when using --create-log-groups flag

### ISSUE THREAD

**Issue by rickybasse** [aws/amazon-ecs-cli#941]
#### Summary
I am running the following for starting a task: 
```
ecs-cli compose --cluster my-cluster --create-log-groups up
```
and the tool fails to recognize the flag `--create-log-groups` with the following error:
```
Incorrect Usage. flag provided but not defined: -create-log-groups

[...]

FATA[0000] flag provided but not defined: -create-log-groups
```

The aforementioned command works removing the flag and creating the log groups manually in AWS. The task is correctly started and it's able to send logs to CloudWatch.

#### Description

* Which specific command was run?
```
ecs-cli compose --cluster my-cluster --create-log-groups up
```
* Which version of the CLI you are using?
```
ecs-cli version 1.17.0 (0301ac8)
```
* Which version of Go are you using?
```
go version go1.12.5 darwin/amd64
```
* What platform are you using to run ECS CLI commands?
```
> sw_vers
ProductName: Mac OS X
ProductVersion: 10.14.6
BuildVersion: 18G103
```

#### Config files

* docker-compose.yml
```yaml
version: '3.0'
services:
  test_task:
    image: my-registry/test-task:latest
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/development/test-task-logs
        awslogs-region: my-region
        awslogs-stream-prefix: ecs

```
* ecs-params.yml
```yaml
version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: my-role
  services:
    test_task:
      essential: true

run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - my-subnets
      security_groups:
        - my-security-groups
```
* ~/.ecs/config: **Not used**

#### Expected Behavior
The tool should recognize the `--create-log-groups` flag.

#### Observed Behavior

```
Incorrect Usage. flag provided but not defined: -create-log-groups

NAME:
   ecs-cli compose - Executes docker-compose-style commands on an ECS cluster.

USAGE:
   ecs-cli compose command [command options] [arguments...]

COMMANDS:
     create      Creates an ECS task definition from your compose file. Note that we do not recommend using plain text environment variables for sensitive information, such as credential data.
     ps, list    Lists all the containers in your cluster that were started by the compose project.
     run         Starts all containers overriding commands with the supplied one-off commands for the containers.
     scale       Scales the number of running tasks to the specified count.
     start       Starts a single task from the task definition created from your compose file.
     stop, down  Stops all the running tasks created by the compose project.
     up          Creates an ECS task definition from your compose file (if it does not already exist) and runs one instance of that task on your cluster (a combination of create and start).
     service     Manage Amazon ECS services with docker-compose-style commands on an ECS cluster.

OPTIONS:
   --file value, -f value          Specifies one or more Docker compose files to use. Defaults to docker-compose.yml file, and an optional docker-compose.override.yml file. [$COMPOSE_FILE]
   --project-name value, -p value  Specifies the project name to use. Defaults to the current directory name. [$COMPOSE_PROJECT_NAME]
   --task-role-arn value           [Optional] Specifies the short name or full Amazon Resource Name (ARN) of the IAM role that containers in this task can assume. All containers in this task are granted the permissions that are specified in this role.
   --ecs-params value              [Optional] Specifies ecs-params file to use. Defaults to ecs-params.yml file, if one exists.
   --registry-creds value          [Optional] Specifies the ecs-registry-creds file to use. Defaults to latest 'ecs-registry-creds' output file, if one exists.
   --verbose, --debug              [Optional] Increase the verbosity of command output to aid in diagnostics.
   --region value, -r value        [Optional] Specifies the AWS region to use. Defaults to the region configured using the configure command
   --ecs-profile value             [Optional] Specifies the name of the ECS profile configuration to use. Defaults to the default profile configuration. [$ECS_PROFILE]
   --aws-profile value             [Optional] Use the AWS credentials from an existing named profile in ~/.aws/credentials. [$AWS_PROFILE]
   --cluster-config value          [Optional] Specifies the name of the ECS cluster configuration to use. Defaults to the default cluster configuration.
   --cluster value, -c value       [Optional] Specifies the ECS cluster name to use. Defaults to the cluster configured using the configure command
   --help, -h                      show help

FATA[0000] flag provided but not defined: -create-log-groups
```
In the `help` section displayed above this argument is actually not listed.
