### ISSUE TITLE
[Help] How to define one container per task per instance

### ISSUE THREAD

**Issue by DuongHieuMAI** [aws/amazon-ecs-cli#961]
Hello guys,

Thank you for making very useful tool for developers.
I've read your document [here](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/application_architecture.html). I can see that containers running across instances.

In my case, I want to set up only one container per instance. For example:
Instance 1 runs front-end.
Instance 2 runs back-end.
I have one docker-compose.yml which defines 2 above services and try to use 2 files ecs-param.yml, one for each task definition as below without success:
```
version: "3"
services:
  back-end:
    container_name: back-end
    build:
      context: ./back-end
    image: back-end:v1

  front-end:
    container_name: front-end
    build:
      context: ./front-end
    image: front-end:v1
```
ecs-front-end-params
```
task_definition:
  ecs_network_mode: awsvpc
  services:
    front-end:
run_params:
  task_placement:
    constraints:
      - type: distinctInstance
```
ecs-back-end-params
```
task_definition:
  ecs_network_mode: awsvpc
  services:
    back-end:
run_params:
  task_placement:
    constraints:
      - type: distinctInstance
```
After runing: ecs-cli compose --ecs-params ./ecs-back-end-params.yml service up
The task had both containers inside. Could you please help me with this architect ? Thank you in advance !
