### ISSUE TITLE
Getting "Fargate requires that 'memory' be defined at the task level" when memory is defined at task level.

### ISSUE THREAD

**Issue by bholzer** [aws/amazon-ecs-cli#982]
Trying to deploy a service to ECS/Fargate, and getting `ERRO[0000] Error registering task definition             error="ClientException: Fargate requires that 'memory' be defined at the task level.\n\tstatus code: 400`

Command: `ecs-cli compose --ecs-params ecs-params.yml service up --launch-type FARGATE`
CLI version 1.18.0 on macOS

Compose file:
```
version: "3.0"
services:
  web:
    image: "338906479759.dkr.ecr.us-east-1.amazonaws.com/image"
    ports:
      - "80:80"
  workers:
    image: "338906479759.dkr.ecr.us-east-1.amazonaws.com/image"
```

ECS params:
```
version: 1
task_definition:
  ecs_network_mode: awsvpc
  task_execution_role: "arn:aws:iam::338906479759:role/task_execution_role"
  task_size:
    cpu_limit: 1024
    memory_limit: 4096
  services:
    web:
      essential: true
    workers:
      essential: true
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - subnet-0000000000000000
        - subnet-1111111111111111
      security_groups:
        - sg-34545667567455366
        - sg-98347502323489749
      assign_public_ip: ENABLED

```

#### Expected Behavior
Memory defined on task should not throw error about memory needing to be defined at task level.

#### Observed Behavior
```
ERRO[0000] Error registering task definition             error="ClientException: Fargate requires that 'memory' be defined at the task level.\n\tstatus code: 400, request id: 104c6bae-14dd-471d-87d0-920e53e9faf5"
ERRO[0000] Create task definition failed                 error="ClientException: Fargate requires that 'memory' be defined at the task level.\n\tstatus code: 400, request id: 104c6bae-14dd-471d-87d0-920e53e9faf5"
FATA[0000] ClientException: Fargate requires that 'memory' be defined at the task level.
	status code: 400, request id: 104c6bae-14dd-471d-87d0-920e53e9faf5
```

I am sure there is some bad configuration I've got going on, but I can't figure out from the error what is actually going on.
