### ISSUE TITLE
Updating ecs-params.yml doesn't trigger new task definition

### ISSUE THREAD

**Issue by agustinsantiago** [aws/amazon-ecs-cli#986]
#### Summary
After making a change in ecs-params.yml (added another service with some secrets), a new task definition isn't created. I had to make a change in docker-compose.yml to trigger the change.

#### Description

* Which specific command was run? (Example: `ecs-cli up --capability-iam --size 2 --launch-type EC2`)
`ecs-cli compose -p my_project_name service up`
* Which version of the CLI you are using? (Run: `ecs-cli --version`)
`ecs-cli version 1.14.1 (f73f9e3)`
* Which version of Go are you using? (Run: `go version`)
None.

* What platform are you using to run ECS CLI commands? (E.g. Linux, macOS, Windows)
macOS

#### Config files

* docker-compose.yml
```
version: '2'
services:
  service_one:
    image: image1
    ports:
      - 80
    cpu_shares: 300
    mem_limit: 150000000
    links:
      - service_two
    logging:
      driver: awslogs
      options:
        awslogs-group: group
        awslogs-region: us-east-1
        awslogs-stream-prefix: service_one
  service_two:
    image: image2
    cpu_shares: 520
    mem_limit: 300000000
    logging:
      driver: awslogs
      options:
        awslogs-group: group
        awslogs-region: us-east-1
        awslogs-stream-prefix: service_two
  service_three:
    image: image3
    cpu_shares: 200
    mem_limit: 100000000
    command: something.sh
    logging:
      driver: awslogs
      options:
        awslogs-group: group
        awslogs-region: us-east-1
        awslogs-stream-prefix: service_three
```
* ecs-params.yml
```
version: 1
task_definition:
  task_execution_role: ecsInstanceRole
  services:
    service_two:
      secrets:
        - value_from: somewhere
          name: SOMEWHERE
    service_three:
      secrets:
        - value_from: somewhere
          name: SOMEWHERE
```

* ~/.ecs/config
```
version: v1
default: my_cluster
clusters:
  my_cluster:
    cluster: my_cluster
    region: us-east-1
    default_launch_type: EC2
```

#### Initial state
I had service_two and service_three configured in docker-compose.yml. I had `ecs-cli compose up` for that one.

#### Expected Behavior
Add service_three to ecs-params.yml . Run `ecs-cli compose up` and get a new definition/version for the task.

#### Observed Behavior
Add service_three to ecs-params.yml . Nothing happens, no new version, no impact in the ecs-params.yml usage in ECS. Making the smallest change in docker-compose.yml and running `ecs-cli compose up` again triggered creating the new definition.
